/* ===================== animals =====================
   The animals that mark each period, keyed by PERIODS id. Each one:
     genus, group      shown as "Dunkleosteus (armoured fish)"
     habitat           marine | freshwater | land | air
     environment       one sentence on where it lived
     size              a comparison a reader can picture
     matters           one sentence on why it matters for the period
     plate, lon, lat   a well-known locality, pinned to a plate at its modern
                       position so that it drifts like a site
     place             the name of that locality
     site              the title of a site in the same period that already tells
                       this animal's story, or null; the panel links to it
     img               a PhyloPic silhouette under img/animals/, or null for the
                       habitat icon. Credits are in SILHOUETTES in js/sources.js
     sources           entry numbers from js/sources.js                         */

const ANIMALS = {
  dev: [
    { genus:"Dunkleosteus", group:"armoured fish", habitat:"marine",
      environment:"It hunted in a warm, shallow sea that covered what is now Ohio, which then lay south of the equator.",
      size:"About 3.4 metres long for a typical adult and about 4.1 metres for the largest known, roughly the length of a small car.",
      matters:"It was one of the first large vertebrates at the top of a food chain, about 360 million years ago, and a 2023 study of its head armour cut the old length estimates of 5 to 10 metres to about 4.",
      plate:"NAM", lon:-81.7, lat:41.4, place:"Cleveland Shale, northeast Ohio",
      site:null, img:"img/animals/dunkleosteus.svg", sources:[7, 8] },
    { genus:"Tiktaalik", group:"lobe-finned fish close to tetrapods", habitat:"freshwater",
      environment:"It lived in shallow streams on a subtropical floodplain, in rock that now lies on Ellesmere Island.",
      size:"Up to about 2.7 metres (nine feet) long, roughly the length of a small rowing boat.",
      matters:"This 375-million-year-old fish has a mobile neck and a working wrist joint inside its fin, and it shows the order in which the features of four-legged animals arose.",
      plate:"NAM", lon:-83, lat:77, place:"Southern Ellesmere Island, Nunavut",
      site:"Tiktaalik", img:"img/animals/tiktaalik.svg", sources:[9, 10, 11] },
    { genus:"Palaeocharinus", group:"trigonotarbid arachnid", habitat:"land",
      environment:"It stalked among low plants around hot springs, and some fossils lie inside hollow plant stems.",
      size:"Body 4 to 6 millimetres long, about the length of a grain of rice.",
      matters:"Its book lungs are the oldest preserved anywhere, so this small predator was breathing air on land in the Early Devonian.",
      plate:"EUR", lon:-2.8, lat:57.4, place:"Rhynie chert, Aberdeenshire, Scotland",
      site:"Rhynie chert", img:"img/animals/palaeocharinus.svg", sources:[12, 13, 14] },
    { genus:"Tutusius", group:"early tetrapod", habitat:"marine",
      environment:"It lived in a brackish tidal estuary inside the Antarctic Circle of the time, with forest growing nearby.",
      size:"About a metre long, judged from a single shoulder bone; roughly the length of a guitar.",
      matters:"It is one of only two Devonian tetrapods known from Africa, and it shows that four-limbed animals lived at polar latitudes as well as in the tropics.",
      plate:"AFR", lon:26, lat:-33, place:"Waterloo Farm, near Makhanda, Eastern Cape",
      site:"Tetrapods outside the tropics", img:null, sources:[15, 16] },
    { genus:"Bothriolepis", group:"armoured fish", habitat:"marine",
      environment:"It lived in a brackish estuary on the southern edge of Laurussia, preserved as the Escuminac Formation at Miguasha.",
      size:"About 44 centimetres long in a reconstructed specimen, with bony armour over the front 16 centimetres; about the length of a forearm and hand.",
      matters:"It is the most abundant vertebrate at Miguasha, where 3,551 of the 7,260 specimens counted in the site museum belong to it.",
      plate:"NAM", lon:-66.37, lat:48.11, place:"Escuminac Formation, Miguasha, Quebec",
      site:null, img:"img/animals/bothriolepis.svg", sources:[17, 18] }
  ],
  car: [
    { genus:"Hylonomus", group:"early reptile", habitat:"land",
      environment:"It lived on the floor of a lycopsid rainforest on a poorly drained coastal plain, where hollow stumps trapped small animals.",
      size:"Small and lizard-like, able to shelter inside a hollow tree stump.",
      matters:"At about 315 million years old it is among the earliest known reptiles, and its bones were found inside the fossil tree stumps at Joggins.",
      plate:"NAM", lon:-64.4, lat:45.7, place:"Joggins Fossil Cliffs, Nova Scotia",
      site:"Joggins Fossil Cliffs", img:null, sources:[19] },
    { genus:"Meganeura", group:"giant dragonfly relative", habitat:"air",
      environment:"It flew over open ground beside the coal forests of what is now central France, about 300 million years ago.",
      size:"Wingspan about 70 centimetres, about the length of an adult's arm.",
      matters:"It is among the largest insects known, and it flew some 30 million years before any vertebrate glided or flew.",
      plate:"EUR", lon:2.75, lat:46.29, place:"Commentry coal basin, Allier, central France",
      site:"Giant insects", img:"img/animals/meganeura.svg", sources:[20, 21] },
    { genus:"Arthropleura", group:"giant millipede relative", habitat:"land",
      environment:"It walked through open woodland on a delta plain near the equator, ground it shared with early tetrapods.",
      size:"Up to 2.63 metres long and 55 centimetres wide, at about 50 kilograms; longer than a king-size bed.",
      matters:"It is the largest arthropod known, and the Northumberland fossil shows it reached that size in the early Carboniferous, before atmospheric oxygen peaked.",
      plate:"EUR", lon:-1.59, lat:55.45, place:"Stainmore Formation, Howick Bay, Northumberland",
      site:null, img:"img/animals/arthropleura.svg", sources:[23, 24] },
    { genus:"Tullimonstrum", group:"Tully monster", habitat:"marine",
      environment:"It swam along a swampy shoreline beside a tropical sea, where carcasses were sealed in iron carbonate nodules.",
      size:"Up to about 30 centimetres (a foot) long, the length of a school ruler.",
      matters:"Known only from Mazon Creek, about 309 to 307 million years old, it was placed with the lampreys in 2016 and outside the vertebrates in 2023, and the question is still open.",
      plate:"NAM", lon:-88.1, lat:41.4, place:"Mazon Creek, Grundy County, Illinois",
      site:"Mazon Creek", img:null, sources:[25, 26, 27] },
    { genus:"Crassigyrinus", group:"early tetrapod", habitat:"freshwater",
      environment:"It hunted in the murky water of coal swamps in what is now Scotland, about 330 million years ago.",
      size:"Two to three metres long with very short limbs, comparable to a mid-sized crocodile.",
      matters:"It is a relative of the first land vertebrates that lived wholly in water, and CT scans published in 2022 rebuilt its crushed skull with large eyes and a crocodile-like shape.",
      plate:"EUR", lon:-3.4, lat:56.1, place:"Coal swamp deposits of central Scotland",
      site:null, img:null, sources:[28, 29] },
    { genus:"Akmonistion", group:"early shark relative", habitat:"marine",
      environment:"Its carcass settled into black mud that became the shales of Bearsden, near Glasgow.",
      size:"About one metre long, roughly the length of a walking stick.",
      matters:"The Bearsden skeleton is 330 million years old and almost intact from snout to tail, which is rare for cartilage, and its last meal of fish is still inside it.",
      plate:"EUR", lon:-4.33, lat:55.92, place:"Manse Burn, Bearsden, Scotland",
      site:null, img:"img/animals/akmonistion.svg", sources:[30, 31] }
  ],
  per: [
    { genus:"Dimetrodon", group:"sail-backed synapsid", habitat:"land",
      environment:"It lived in the swampy lowlands of what is now north Texas and Oklahoma, where it fed on other vertebrates.",
      size:"About 3.5 metres long and 100 to 150 kilograms, with a sail nearly a metre tall; about the length of two bicycles end to end.",
      matters:"It was the first large land predator among the amniotes, 279 to 272 million years ago in Texas, and as a synapsid it stands on the mammal side of the family tree.",
      plate:"NAM", lon:-99.2, lat:33.6, place:"Craddock Bonebed, Baylor County, Texas",
      site:null, img:"img/animals/dimetrodon.svg", sources:[32, 33] },
    { genus:"Lystrosaurus", group:"dicynodont therapsid", habitat:"land",
      environment:"It lived on the river plains of the Karoo Basin as they grew hotter and drier towards the extinction.",
      size:"Mostly about the size of a pig, with some animals 1.8 to 2.4 metres long; the largest Permian skull is 39 centimetres long.",
      matters:"It arose just before the end-Permian extinction 252 million years ago and crossed it, and its numbers rose sharply in the earliest Triassic.",
      plate:"AFR", lon:24, lat:-32, place:"Karoo Basin, South Africa",
      site:"The Karoo Basin", img:"img/animals/lystrosaurus.svg", sources:[34, 35] },
    { genus:"Moschops", group:"dinocephalian therapsid", habitat:"land",
      environment:"It browsed at ground level on the river plains of the Karoo Basin, about 265 to 260 million years ago.",
      size:"About 1.9 metres from snout to hip and an estimated 330 kilograms, about the weight of a grand piano.",
      matters:"Its thick skull roof and bone-enclosed brain point to head-butting, and the dinocephalians vanished from the Karoo in a mid-Permian extinction dated to about 260 million years ago.",
      plate:"AFR", lon:26.5, lat:-33.1, place:"Tapinocephalus Assemblage Zone, north of Makhanda (Grahamstown), Eastern Cape",
      site:null, img:"img/animals/moschops.svg", sources:[36, 37] },
    { genus:"Helicoprion", group:"spiral-toothed ratfish relative", habitat:"marine",
      environment:"It swam in Early Permian seas worldwide, and the key specimen comes from the Phosphoria Formation of Idaho, about 270 million years old.",
      size:"The Idaho tooth whorl is 23 centimetres across with 117 teeth, about the size of a dinner plate, and the largest whorls imply jaws more than 50 centimetres long.",
      matters:"CT scans in 2013 showed that the whorl filled the whole lower jaw and placed Helicoprion among the relatives of living ratfish, after a century of guessed reconstructions.",
      plate:"NAM", lon:-111.2, lat:42.3, place:"Waterloo Mine, near Montpelier, Idaho",
      site:null, img:"img/animals/helicoprion.svg", sources:[38, 39] },
    { genus:"Mesosaurus", group:"early aquatic reptile", habitat:"marine",
      environment:"It swam in a salty inland sea (the Irati-Whitehill Sea) that covered parts of what are now Brazil, Uruguay, Namibia and South Africa.",
      size:"Usually under a metre long, about the length of an arm.",
      matters:"Mesosaurs were the first amniotes to return to life in water, and they occur only around this one Early Permian sea, on two continents now an ocean apart.",
      plate:"SAM", lon:-50.5, lat:-25.5, place:"Irati Formation, southern Brazil",
      site:null, img:null, sources:[40, 41, 42] }
  ],
  pgn: [
    { genus:"Basilosaurus", group:"early whale", habitat:"marine",
      environment:"About 37 million years ago a shallow sea covered what is now the Western Desert of Egypt, and the smaller whale Dorudon calved there.",
      size:"15 to 18 metres long, about the length of an articulated lorry.",
      matters:"It lived wholly at sea yet still carried tiny hind legs, and stomach contents show it ate young Dorudon, which places it among the largest predators known from late Eocene seas.",
      plate:"AFR", lon:30.2, lat:29.3, place:"Wadi Al-Hitan (Whale Valley), Egypt",
      site:null, img:"img/animals/basilosaurus.svg", sources:[44, 45, 46] },
    { genus:"Pakicetus", group:"early whale", habitat:"land",
      environment:"Around 50 million years ago it lived beside rivers on the northern edge of India, next to the last shallow remnants of the Tethys Sea as India closed on Asia.",
      size:"About the size of a wolf.",
      matters:"One of the oldest whales known: a four-legged land animal whose ear region already carries the bony wall found in living whales.",
      plate:"IND", lon:72.4, lat:33.6, place:"Kuldana Formation, Kala Chitta Hills, northern Pakistan",
      site:null, img:"img/animals/pakicetus.svg", sources:[45, 47, 48, 49] },
    { genus:"Palaeeudyptes", group:"giant penguin", habitat:"marine",
      environment:"A storm-swept tidal shelf off the Antarctic Peninsula in the late Eocene.",
      size:"About 2 metres from bill tip to toes, longer than most people are tall, and about 115 kilograms.",
      matters:"The largest and heaviest penguin known when its bones were described in 2014, from rocks on Seymour Island that hold at least eleven species of Eocene penguin.",
      plate:"ANT", lon:-56.7, lat:-64.25, place:"Submeseta Formation, Seymour (Marambio) Island, Antarctic Peninsula",
      site:null, img:null, sources:[50, 51] },
    { genus:"Knightia", group:"herring relative", habitat:"freshwater",
      environment:"Warm subtropical lakes about 52 million years ago, fringed with palms and sycamores and shared with crocodiles, gars and stingrays.",
      size:"About 15 centimetres long as an adult, the length of a hand; the largest reach 25 centimetres.",
      matters:"The most common fish of Fossil Lake and, by the National Park Service's account, the most commonly found complete vertebrate fossil in the world; single slabs hold up to 100 fish per square metre, killed together.",
      plate:"NAM", lon:-110, lat:41.5, place:"Green River Formation, Fossil Butte, Wyoming",
      site:"Green River lakes", img:"img/animals/knightia.svg", sources:[52, 53] },
    { genus:"Titanoboa", group:"giant boa", habitat:"freshwater",
      environment:"Rivers of the oldest known rainforest in tropical South America, 60 to 58 million years ago, where it lived much as an anaconda does now.",
      size:"About 13 metres long and 1,135 kilograms, longer than a city bus.",
      matters:"The largest snake known; a cold-blooded animal of this size needs a mean annual temperature of 30 to 34°C, so its bones give a temperature reading for the Paleocene tropics.",
      plate:"SAM", lon:-72.7, lat:11.1, place:"Cerrejón coal mine, La Guajira, Colombia",
      site:null, img:"img/animals/titanoboa.svg", sources:[54, 55] },
    { genus:"Eurohippus", group:"early horse relative", habitat:"land",
      environment:"Warm humid forest around a deep volcanic crater lake with oxygen-free bottom water, about 48 million years ago.",
      size:"About 30 centimetres at the shoulder, the height of a small dog.",
      matters:"Messel has yielded at least 39 skeletons, eight of them pregnant mares, and one foetus is the earliest and best preserved known from any fossil horse relative.",
      plate:"EUR", lon:8.75, lat:49.9, place:"Messel Pit, Hesse, Germany",
      site:"Messel Pit", img:null, sources:[56, 57] },
    { genus:"Onychonycteris", group:"early bat", habitat:"air",
      environment:"Forest around Fossil Lake in what is now Wyoming, about 52 million years ago.",
      size:"A wingspan of about 30 centimetres and a weight near 40 grams, a little less than a golf ball.",
      matters:"The most primitive bat known: it could fly, its ear shows no sign of echolocation, and it kept claws on all five fingers for climbing, so flight came first.",
      plate:"NAM", lon:-110, lat:41.5, place:"Green River Formation, Fossil Butte, Wyoming",
      site:"Green River lakes", img:"img/animals/onychonycteris.svg", sources:[58, 59, 60] },
    { genus:"Gastornis", group:"giant flightless bird", habitat:"land",
      environment:"Subtropical lowland forest; the Washington tracks were pressed into a riverbank about 50 million years ago.",
      size:"About 2.1 metres tall and roughly 170 kilograms, a little taller than a standard doorway.",
      matters:"Clawless tracks and the carbon isotopes in its bones mark this giant as a plant eater, and it ranged north to Ellesmere Island, where it probably wintered through the polar dark.",
      plate:"NAM", lon:-122.1, lat:48.8, place:"Chuckanut Formation, Whatcom County, Washington",
      site:null, img:"img/animals/gastornis.svg", sources:[61, 62, 63, 64] },
    { genus:"Paraceratherium", group:"hornless giant rhinoceros", habitat:"land",
      environment:"Open woodland across central Asia in the Oligocene; the skull from the Linxia Basin is 26.5 million years old.",
      size:"The largest species stood about 4.8 metres at the shoulder, higher than a double-decker bus, and weighed about 17 tonnes.",
      matters:"One of the largest land mammals that ever lived; close relatives in Pakistan and north-west China show the giants walked across the Tibetan region, which still lay low in the Oligocene.",
      plate:"CHI", lon:103.2, lat:35.6, place:"Jiaozigou Formation, Linxia Basin, Gansu, China",
      site:null, img:"img/animals/paraceratherium.svg", sources:[65, 66] },
    { genus:"Pelagornis", group:"bony-toothed seabird", habitat:"air",
      environment:"Open sea off what is now South Carolina, 25 to 28 million years ago.",
      size:"A wingspan of about 6.4 metres, twice that of a royal albatross.",
      matters:"The widest wingspan known in any bird, carried by a long-range glider whose lineage had already reached giant size by about 50 million years ago.",
      plate:"NAM", lon:-80.0, lat:32.9, place:"Chandler Bridge Formation, Charleston, South Carolina",
      site:null, img:"img/animals/pelagornis.svg", sources:[67, 68] }
  ]
};
