/* ===================== animals =====================
   The animals that mark each period, keyed by PERIODS id. Each one:
     genus, group      shown as "Dunkleosteus (armoured fish)"
     habitat           marine | freshwater | land | air
     environment       one sentence on where it lived
     size              a comparison a reader can picture
     matters           one sentence on why it matters for the period
     plate, lon, lat   a well-known locality, pinned to a plate at its modern
                       position so that it drifts like a site
     place             the name of that locality
     site              the title of a site in the same period that already tells
                       this animal's story, or null; the panel links to it
     img               a PhyloPic silhouette under img/animals/, or null for the
                       habitat icon. Credits are in SILHOUETTES in js/sources.js
     sources           entry numbers from js/sources.js                         */

const ANIMALS = {
  cam: [
    { genus:"Anomalocaris", group:"swimming predator, an early arthropod relative", habitat:"marine",
      environment:"It swam in well-lit open water above the sea floor of the Burgess Shale basin, in what is now British Columbia.",
      size:"The most complete specimen is 25 centimetres long, a little shorter than a school ruler. Isolated claws and mouthparts come from larger animals, and the Royal Ontario Museum puts the biggest at about a metre.",
      matters:"Stalked eyes, spined grasping claws and a ring of toothed plates round the mouth mark it as one of the first large swimming hunters. Modelling of the claws in 2023 found them built to snatch soft prey at speed and likely to be damaged by hard shell.",
      plate:"NAM", lon:-116.5, lat:51.4, place:"Burgess Shale, Yoho National Park, British Columbia",
      site:"Burgess Shale", img:"img/animals/anomalocaris.svg", sources:[95, 96] },
    { genus:"Opabinia", group:"five-eyed arthropod relative", habitat:"marine",
      environment:"It swam over the muddy sea floor of the Burgess Shale basin and hunted small prey there.",
      size:"Up to 10 centimetres long (101 millimetres), about the length of a finger.",
      matters:"It carried five eyes and a flexible trunk four times the length of its head, tipped with a claw that passed food back to the mouth. It sits low on the stem of the arthropods, and until 2022 it was the only described member of its family.",
      plate:"NAM", lon:-116.5, lat:51.4, place:"Burgess Shale, Yoho National Park, British Columbia",
      site:"Burgess Shale", img:"img/animals/opabinia.svg", sources:[97, 98] },
    { genus:"Hallucigenia", group:"spined worm, a velvet worm relative", habitat:"marine",
      environment:"It walked on the sea floor of the Burgess Shale basin and is often found with the sponge Vauxia, which it may have climbed to feed.",
      size:"Up to 3 centimetres long, about the length of a paperclip.",
      matters:"It was first reconstructed upside down and back to front, walking on its spines. It is now placed on the stem of the velvet worms, and its head, with a pair of simple eyes and a throat lined with teeth, was described only in 2015.",
      plate:"NAM", lon:-116.5, lat:51.4, place:"Burgess Shale, Yoho National Park, British Columbia",
      site:"Burgess Shale", img:null, sources:[99, 100] },
    { genus:"Pikaia", group:"early chordate", habitat:"marine",
      environment:"It probably swam freely above the Burgess Shale sea floor and spent part of its time resting on the mud.",
      size:"Up to 5.5 centimetres long, about the length of a little finger.",
      matters:"About 100 zigzag muscle blocks run down its body, the arrangement that backboned animals still swim with. A 2024 restudy found a gut and a dorsal nerve cord and showed that earlier reconstructions had drawn the animal upside down.",
      plate:"NAM", lon:-116.5, lat:51.4, place:"Burgess Shale, Yoho National Park, British Columbia",
      site:"Burgess Shale", img:"img/animals/pikaia.svg", sources:[101, 102, 103] },
    { genus:"Haikouichthys", group:"jawless early fish", habitat:"marine",
      environment:"It swam in the shallow Cambrian sea that laid down the Chengjiang beds of Yunnan.",
      size:"A small fish. The papers read for this entry give no measured length.",
      matters:"At 518 million years old it is the oldest fish yet found. The fossils show eyes, gills, muscle blocks and a stiffening rod along the back with separate vertebral elements, which places it close to the base of the vertebrates.",
      plate:"CHI", lon:102.6, lat:24.7, place:"Chengjiang fossil beds, Yunnan, China",
      site:"Chengjiang", img:"img/animals/haikouichthys.svg", sources:[104, 105, 106] },
    { genus:"Redlichia", group:"trilobite", habitat:"marine",
      environment:"It lived on a shallow sea floor on the eastern margin of Gondwana, in rock that now lies on Kangaroo Island.",
      size:"Up to 25 centimetres long, about the width of a dinner plate.",
      matters:"Redlichia rex is one of the largest trilobites of the Cambrian. Some specimens keep their antennae and legs, and the legs carry spined bases that shredded or crushed food.",
      plate:"AUS", lon:137.5, lat:-35.7, place:"Emu Bay Shale, Kangaroo Island, South Australia",
      site:"Emu Bay Shale", img:null, sources:[107, 108] },
    { genus:"Paradoxides", group:"trilobite", habitat:"marine",
      environment:"It crawled over the shallow sea floor off Avalonia, a small continent whose pieces now lie in Wales, Newfoundland and New England.",
      size:"The largest reached about half a metre, the length of a forearm and hand. Museum specimens of Paradoxides davidis are mostly 16 to 24 centimetres long.",
      matters:"Paradoxides turns up in Wales, Newfoundland, Sweden and Spain, and geologists use it to tie together Middle Cambrian rocks that now lie on both sides of the Atlantic. Healed wounds on Welsh and Newfoundland specimens are large enough that the attackers may have been other Paradoxides.",
      plate:"EUR", lon:-5.2, lat:51.87, place:"Porth-y-rhaw, near St Davids, Pembrokeshire, Wales",
      site:null, img:null, sources:[109, 110, 111] }
  ],
  ord: [
    { genus:"Aegirocassis", group:"giant filter-feeding arthropod relative", habitat:"marine",
      environment:"It swam in the Early Ordovician sea that covered what is now southern Morocco, and it strained plankton from the water.",
      size:"More than 2 metres long, longer than a tall adult lying down.",
      matters:"It sieved plankton through comb-like limbs on its head, a way of feeding that points to rich plankton in Early Ordovician seas. Each body segment carried an upper and a lower pair of flaps, which settled how the flaps of radiodonts relate to the legs of arthropods.",
      plate:"AFR", lon:-6, lat:31, place:"Fezouata Shale, near Zagora, Morocco",
      site:"Fezouata Biota", img:null, sources:[112, 113] },
    { genus:"Isotelus", group:"trilobite", habitat:"marine",
      environment:"It lived on a nearshore carbonate sea floor on the equator, where it probably ploughed shallow furrows through the sediment as a predator and scavenger.",
      size:"72 centimetres from head shield to tail, about as long as an adult's arm.",
      matters:"The Churchill specimen of Isotelus rex is the largest complete trilobite ever found. Its lineage died out in the end-Ordovician extinction, probably because its drifting larvae could not cope with rapid cooling and the loss of tropical shelf seas.",
      plate:"NAM", lon:-94.2, lat:58.8, place:"Churchill River Group, Hudson Bay shore near Churchill, Manitoba",
      site:null, img:"img/animals/isotelus.svg", sources:[114, 115] },
    { genus:"Endoceras", group:"straight-shelled nautiloid", habitat:"marine",
      environment:"A swimming predator of Ordovician shelf seas, it carried a long, straight, chambered cone of a shell.",
      size:"The longest shell fragment measures 3 metres, and the complete shell is reconstructed at 5.7 metres, longer than a family car. A reported 10-metre shell was never collected or photographed, and specialists doubt it.",
      matters:"Ordovician endocerids are the largest cephalopod fossils known. Most species in the group were far smaller.",
      plate:"NAM", lon:-88.4, lat:41.5, place:"Platteville, Illinois (display specimen, University of Michigan Museum of Natural History)",
      site:null, img:"img/animals/endoceras.svg", sources:[116, 117] },
    { genus:"Sacabambaspis", group:"armoured jawless fish", habitat:"marine",
      environment:"It lived in tidal and shallow subtidal water along the coast of Gondwana.",
      size:"Roughly 35 centimetres long, a little longer than a school ruler.",
      matters:"It is the earliest vertebrate known from whole, articulated skeletons, with bony head shields and a scaled trunk and tail. Arandaspids lived only along Gondwanan shores, and they vanish from the record when the end-Ordovician glaciation begins.",
      plate:"SAM", lon:-65.8, lat:-17.8, place:"Anzaldo Formation, Sacabambilla, Cochabamba, Bolivia",
      site:null, img:"img/animals/sacabambaspis.svg", sources:[118, 119, 120] },
    { genus:"Pentecopterus", group:"sea scorpion", habitat:"marine",
      environment:"It lived in a flooded meteorite crater 5.6 kilometres across on the tropical coast of Laurentia, in low-oxygen and possibly brackish water.",
      size:"Most were 75 to 100 centimetres long, and the largest body plates point to animals of 1.7 metres, the height of an adult.",
      matters:"It is the oldest described sea scorpion, from rocks between 467 and 458 million years old. It was already large and belonged to an advanced branch of the group, so sea scorpions must have diversified earlier still.",
      plate:"NAM", lon:-91.8, lat:43.3, place:"Winneshiek Shale, Decorah, Iowa",
      site:null, img:"img/animals/pentecopterus.svg", sources:[121, 122] },
    { genus:"Promissum", group:"conodont, an eel-like jawless vertebrate", habitat:"marine",
      environment:"It swam in cold, still water over an oxygen-starved sea floor, just after the Hirnantian ice sheet had melted back.",
      size:"About 40 centimetres long. The other conodont animals known from whole bodies, from Scotland, are 4 centimetres long.",
      matters:"Only four places in the world preserve the soft tissue of conodonts. This one keeps its eyes, V-shaped muscle blocks and liver, and its set of teeth is the largest and most complex known. The lineage was a cold-water Gondwanan one that came through the end-Ordovician extinction.",
      plate:"AFR", lon:18.9, lat:-32.2, place:"Soom Shale, Keurbos farm near Clanwilliam, South Africa",
      site:null, img:null, sources:[123, 124, 125] },
    { genus:"Didymograptus", group:"graptolite, a floating colony", habitat:"marine",
      environment:"Colonies drifted in the upper layers of the open ocean, where the tiny animals in each tube fed on single-celled plankton.",
      size:"About 2 centimetres long, the size of a small coin. Each colony forms two hanging branches, shaped like a tuning fork.",
      matters:"Graptolites took to floating at the start of the Ordovician and were among the first animals to colonise the open sea. Tuning-fork graptolites are common in rocks about 460 million years old in both Pembrokeshire and Belgium, and the Llanvirn rocks they mark were named in 1881 after a farm at Abereiddi Bay.",
      plate:"EUR", lon:-5.2, lat:51.94, place:"Abereiddi Bay, Pembrokeshire, Wales",
      site:null, img:null, sources:[126, 127] }
  ],
  dev: [
    { genus:"Dunkleosteus", group:"armoured fish", habitat:"marine",
      environment:"It hunted in a warm, shallow sea that covered what is now Ohio, which then lay south of the equator.",
      size:"About 3.4 metres long for a typical adult and about 4.1 metres for the largest known, roughly the length of a small car.",
      matters:"It was one of the first large vertebrates at the top of a food chain, about 360 million years ago, and a 2023 study of its head armour cut the old length estimates of 5 to 10 metres to about 4.",
      plate:"NAM", lon:-81.7, lat:41.4, place:"Cleveland Shale, northeast Ohio",
      site:null, img:"img/animals/dunkleosteus.svg", sources:[7, 8] },
    { genus:"Tiktaalik", group:"lobe-finned fish close to tetrapods", habitat:"freshwater",
      environment:"It lived in shallow streams on a subtropical floodplain, in rock that now lies on Ellesmere Island.",
      size:"Up to about 2.7 metres (nine feet) long, roughly the length of a small rowing boat.",
      matters:"This 375-million-year-old fish has a mobile neck and a working wrist joint inside its fin, and it shows the order in which the features of four-legged animals arose.",
      plate:"NAM", lon:-83, lat:77, place:"Southern Ellesmere Island, Nunavut",
      site:"Tiktaalik", img:"img/animals/tiktaalik.svg", sources:[9, 10, 11] },
    { genus:"Palaeocharinus", group:"early arachnid", habitat:"land",
      environment:"It stalked among low plants around hot springs, and some fossils lie inside hollow plant stems.",
      size:"Body 4 to 6 millimetres long, about the length of a grain of rice.",
      matters:"Its book lungs are the oldest preserved anywhere, so this small predator was breathing air on land in the Early Devonian.",
      plate:"EUR", lon:-2.8, lat:57.4, place:"Rhynie chert, Aberdeenshire, Scotland",
      site:"Rhynie chert", img:"img/animals/palaeocharinus.svg", sources:[12, 13, 14] },
    { genus:"Tutusius", group:"early tetrapod", habitat:"marine",
      environment:"It lived in a brackish tidal estuary inside the Antarctic Circle of the time, with forest growing nearby.",
      size:"About a metre long, judged from a single shoulder bone; roughly the length of a guitar.",
      matters:"It is one of only two Devonian tetrapods known from Africa, and it shows that four-limbed animals lived at polar latitudes as well as in the tropics.",
      plate:"AFR", lon:26, lat:-33, place:"Waterloo Farm, near Makhanda, Eastern Cape",
      site:"Tetrapods outside the tropics", img:null, sources:[15, 16] },
    { genus:"Bothriolepis", group:"armoured fish", habitat:"marine",
      environment:"It lived in a brackish estuary on the southern edge of Laurussia, preserved as the Escuminac Formation at Miguasha.",
      size:"About 44 centimetres long in a reconstructed specimen, with bony armour over the front 16 centimetres; about the length of a forearm and hand.",
      matters:"It is the most abundant vertebrate at Miguasha, where 3,551 of the 7,260 specimens counted in the site museum belong to it.",
      plate:"NAM", lon:-66.37, lat:48.11, place:"Escuminac Formation, Miguasha, Quebec",
      site:null, img:"img/animals/bothriolepis.svg", sources:[17, 18] }
  ],
  car: [
    { genus:"Hylonomus", group:"early reptile", habitat:"land",
      environment:"It lived on the floor of a lycopsid rainforest on a poorly drained coastal plain, where hollow stumps trapped small animals.",
      size:"Small and lizard-like, able to shelter inside a hollow tree stump.",
      matters:"At about 315 million years old it is among the earliest known reptiles, and its bones were found inside the fossil tree stumps at Joggins.",
      plate:"NAM", lon:-64.4, lat:45.7, place:"Joggins Fossil Cliffs, Nova Scotia",
      site:"Joggins Fossil Cliffs", img:null, sources:[19] },
    { genus:"Meganeura", group:"giant dragonfly relative", habitat:"air",
      environment:"It flew over open ground beside the coal forests of what is now central France, about 300 million years ago.",
      size:"Wingspan about 70 centimetres, about the length of an adult's arm.",
      matters:"It is among the largest insects known, and it flew some 30 million years before any vertebrate glided or flew.",
      plate:"EUR", lon:2.75, lat:46.29, place:"Commentry coal basin, Allier, central France",
      site:"Giant insects", img:"img/animals/meganeura.svg", sources:[20, 21] },
    { genus:"Arthropleura", group:"giant millipede relative", habitat:"land",
      environment:"It walked through open woodland on a delta plain near the equator, ground it shared with early tetrapods.",
      size:"Up to 2.63 metres long and 55 centimetres wide, at about 50 kilograms; longer than a king-size bed.",
      matters:"It is the largest arthropod known, and the Northumberland fossil shows it reached that size in the early Carboniferous, before atmospheric oxygen peaked.",
      plate:"EUR", lon:-1.59, lat:55.45, place:"Stainmore Formation, Howick Bay, Northumberland",
      site:null, img:"img/animals/arthropleura.svg", sources:[23, 24] },
    { genus:"Tullimonstrum", group:"Tully monster", habitat:"marine",
      environment:"It swam along a swampy shoreline beside a tropical sea, where carcasses were sealed in iron carbonate nodules.",
      size:"Up to about 30 centimetres (a foot) long, the length of a school ruler.",
      matters:"Known only from Mazon Creek, about 309 to 307 million years old, it was placed with the lampreys in 2016 and outside the vertebrates in 2023, and the question is still open.",
      plate:"NAM", lon:-88.1, lat:41.4, place:"Mazon Creek, Grundy County, Illinois",
      site:"Mazon Creek", img:null, sources:[25, 26, 27] },
    { genus:"Crassigyrinus", group:"early tetrapod", habitat:"freshwater",
      environment:"It hunted in the murky water of coal swamps in what is now Scotland, about 330 million years ago.",
      size:"Two to three metres long with very short limbs, comparable to a mid-sized crocodile.",
      matters:"It is a relative of the first land vertebrates that lived wholly in water, and CT scans published in 2022 rebuilt its crushed skull with large eyes and a crocodile-like shape.",
      plate:"EUR", lon:-3.4, lat:56.1, place:"Coal swamp deposits of central Scotland",
      site:null, img:null, sources:[28, 29] },
    { genus:"Akmonistion", group:"early shark relative", habitat:"marine",
      environment:"Its carcass settled into black mud that became the shales of Bearsden, near Glasgow.",
      size:"About one metre long, roughly the length of a walking stick.",
      matters:"The Bearsden skeleton is 330 million years old and almost intact from snout to tail, which is rare for cartilage, and its last meal of fish is still inside it.",
      plate:"EUR", lon:-4.33, lat:55.92, place:"Manse Burn, Bearsden, Scotland",
      site:null, img:"img/animals/akmonistion.svg", sources:[30, 31] }
  ],
  per: [
    { genus:"Dimetrodon", group:"sail-backed mammal relative", habitat:"land",
      environment:"It lived in the swampy lowlands of what is now north Texas and Oklahoma, where it fed on other vertebrates.",
      size:"About 3.5 metres long and 100 to 150 kilograms, with a sail nearly a metre tall; about the length of two bicycles end to end.",
      matters:"It was the first large land predator among the amniotes, 279 to 272 million years ago in Texas, and as a synapsid it stands on the mammal side of the family tree.",
      plate:"NAM", lon:-99.2, lat:33.6, place:"Craddock Bonebed, Baylor County, Texas",
      site:null, img:"img/animals/dimetrodon.svg", sources:[32, 33] },
    { genus:"Lystrosaurus", group:"tusked mammal relative", habitat:"land",
      environment:"It lived on the river plains of the Karoo Basin as they grew hotter and drier towards the extinction.",
      size:"Mostly about the size of a pig, with some animals 1.8 to 2.4 metres long; the largest Permian skull is 39 centimetres long.",
      matters:"It arose just before the end-Permian extinction 252 million years ago and crossed it, and its numbers rose sharply in the earliest Triassic.",
      plate:"AFR", lon:24, lat:-32, place:"Karoo Basin, South Africa",
      site:"The Karoo Basin", img:"img/animals/lystrosaurus.svg", sources:[34, 35] },
    { genus:"Moschops", group:"thick-skulled mammal relative", habitat:"land",
      environment:"It browsed at ground level on the river plains of the Karoo Basin, about 265 to 260 million years ago.",
      size:"About 1.9 metres from snout to hip and an estimated 330 kilograms, about the weight of a grand piano.",
      matters:"Its thick skull roof and bone-enclosed brain point to head-butting, and the dinocephalians vanished from the Karoo in a mid-Permian extinction dated to about 260 million years ago.",
      plate:"AFR", lon:26.5, lat:-33.1, place:"Tapinocephalus Assemblage Zone, north of Makhanda (Grahamstown), Eastern Cape",
      site:null, img:"img/animals/moschops.svg", sources:[36, 37] },
    { genus:"Helicoprion", group:"spiral-toothed ratfish relative", habitat:"marine",
      environment:"It swam in Early Permian seas worldwide, and the key specimen comes from the Phosphoria Formation of Idaho, about 270 million years old.",
      size:"The Idaho tooth whorl is 23 centimetres across with 117 teeth, about the size of a dinner plate, and the largest whorls imply jaws more than 50 centimetres long.",
      matters:"CT scans in 2013 showed that the whorl filled the whole lower jaw and placed Helicoprion among the relatives of living ratfish, after a century of guessed reconstructions.",
      plate:"NAM", lon:-111.2, lat:42.3, place:"Waterloo Mine, near Montpelier, Idaho",
      site:null, img:"img/animals/helicoprion.svg", sources:[38, 39] },
    { genus:"Mesosaurus", group:"early aquatic reptile", habitat:"marine",
      environment:"It swam in a salty inland sea (the Irati-Whitehill Sea) that covered parts of what are now Brazil, Uruguay, Namibia and South Africa.",
      size:"Usually under a metre long, about the length of an arm.",
      matters:"Mesosaurs were the first amniotes to return to life in water, and they occur only around this one Early Permian sea, on two continents now an ocean apart.",
      plate:"SAM", lon:-50.5, lat:-25.5, place:"Irati Formation, southern Brazil",
      site:null, img:null, sources:[40, 41, 42] }
  ],
  pgn: [
    { genus:"Basilosaurus", group:"early whale", habitat:"marine",
      environment:"About 37 million years ago a shallow sea covered what is now the Western Desert of Egypt, and the smaller whale Dorudon calved there.",
      size:"15 to 18 metres long, about the length of an articulated lorry.",
      matters:"It lived wholly at sea yet still carried tiny hind legs, and stomach contents show it ate young Dorudon, which places it among the largest predators known from late Eocene seas.",
      plate:"AFR", lon:30.2, lat:29.3, place:"Wadi Al-Hitan (Whale Valley), Egypt",
      site:null, img:"img/animals/basilosaurus.svg", sources:[44, 45, 46] },
    { genus:"Pakicetus", group:"early whale", habitat:"land",
      environment:"Around 50 million years ago it lived beside rivers on the northern edge of India, next to the last shallow remnants of the Tethys Sea as India closed on Asia.",
      size:"About the size of a wolf.",
      matters:"One of the oldest whales known: a four-legged land animal whose ear region already carries the bony wall found in living whales.",
      plate:"IND", lon:72.4, lat:33.6, place:"Kuldana Formation, Kala Chitta Hills, northern Pakistan",
      site:null, img:"img/animals/pakicetus.svg", sources:[45, 47, 48, 49] },
    { genus:"Palaeeudyptes", group:"giant penguin", habitat:"marine",
      environment:"A storm-swept tidal shelf off the Antarctic Peninsula in the late Eocene.",
      size:"About 2 metres from bill tip to toes, longer than most people are tall, and about 115 kilograms.",
      matters:"The largest and heaviest penguin known when its bones were described in 2014, from rocks on Seymour Island that hold at least eleven species of Eocene penguin.",
      plate:"ANT", lon:-56.7, lat:-64.25, place:"Submeseta Formation, Seymour (Marambio) Island, Antarctic Peninsula",
      site:null, img:null, sources:[50, 51] },
    { genus:"Knightia", group:"herring relative", habitat:"freshwater",
      environment:"Warm subtropical lakes about 52 million years ago, fringed with palms and sycamores and shared with crocodiles, gars and stingrays.",
      size:"About 15 centimetres long as an adult, the length of a hand; the largest reach 25 centimetres.",
      matters:"The most common fish of Fossil Lake and, by the National Park Service's account, the most commonly found complete vertebrate fossil in the world; single slabs hold up to 100 fish per square metre, killed together.",
      plate:"NAM", lon:-110, lat:41.5, place:"Green River Formation, Fossil Butte, Wyoming",
      site:"Green River lakes", img:"img/animals/knightia.svg", sources:[52, 53] },
    { genus:"Titanoboa", group:"giant boa", habitat:"freshwater",
      environment:"Rivers of the oldest known rainforest in tropical South America, 60 to 58 million years ago, where it lived much as an anaconda does now.",
      size:"About 13 metres long and 1,135 kilograms, longer than a city bus.",
      matters:"The largest snake known; a cold-blooded animal of this size needs a mean annual temperature of 30 to 34°C, so its bones give a temperature reading for the Paleocene tropics.",
      plate:"SAM", lon:-72.7, lat:11.1, place:"Cerrejón coal mine, La Guajira, Colombia",
      site:null, img:"img/animals/titanoboa.svg", sources:[54, 55] },
    { genus:"Eurohippus", group:"early horse relative", habitat:"land",
      environment:"Warm humid forest around a deep volcanic crater lake with oxygen-free bottom water, about 48 million years ago.",
      size:"About 30 centimetres at the shoulder, the height of a small dog.",
      matters:"Messel has yielded at least 39 skeletons, eight of them pregnant mares, and one foetus is the earliest and best preserved known from any fossil horse relative.",
      plate:"EUR", lon:8.75, lat:49.9, place:"Messel Pit, Hesse, Germany",
      site:"Messel Pit", img:null, sources:[56, 57] },
    { genus:"Onychonycteris", group:"early bat", habitat:"air",
      environment:"Forest around Fossil Lake in what is now Wyoming, about 52 million years ago.",
      size:"A wingspan of about 30 centimetres and a weight near 40 grams, a little less than a golf ball.",
      matters:"The most primitive bat known: it could fly, its ear shows no sign of echolocation, and it kept claws on all five fingers for climbing, so flight came first.",
      plate:"NAM", lon:-110, lat:41.5, place:"Green River Formation, Fossil Butte, Wyoming",
      site:"Green River lakes", img:"img/animals/onychonycteris.svg", sources:[58, 59, 60] },
    { genus:"Gastornis", group:"giant flightless bird", habitat:"land",
      environment:"Subtropical lowland forest; the Washington tracks were pressed into a riverbank about 50 million years ago.",
      size:"About 2.1 metres tall and roughly 170 kilograms, a little taller than a standard doorway.",
      matters:"Clawless tracks and the carbon isotopes in its bones mark this giant as a plant eater, and it ranged north to Ellesmere Island, where it probably wintered through the polar dark.",
      plate:"NAM", lon:-122.1, lat:48.8, place:"Chuckanut Formation, Whatcom County, Washington",
      site:null, img:"img/animals/gastornis.svg", sources:[61, 62, 63, 64] },
    { genus:"Paraceratherium", group:"hornless giant rhinoceros", habitat:"land",
      environment:"Open woodland across central Asia in the Oligocene; the skull from the Linxia Basin is 26.5 million years old.",
      size:"The largest species stood about 4.8 metres at the shoulder, higher than a double-decker bus, and weighed about 17 tonnes.",
      matters:"One of the largest land mammals that ever lived; close relatives in Pakistan and north-west China show the giants walked across the Tibetan region, which still lay low in the Oligocene.",
      plate:"CHI", lon:103.2, lat:35.6, place:"Jiaozigou Formation, Linxia Basin, Gansu, China",
      site:null, img:"img/animals/paraceratherium.svg", sources:[65, 66] },
    { genus:"Pelagornis", group:"bony-toothed seabird", habitat:"air",
      environment:"Open sea off what is now South Carolina, 25 to 28 million years ago.",
      size:"A wingspan of about 6.4 metres, twice that of a royal albatross.",
      matters:"The widest wingspan known in any bird, carried by a long-range glider whose lineage had already reached giant size by about 50 million years ago.",
      plate:"NAM", lon:-80.0, lat:32.9, place:"Chandler Bridge Formation, Charleston, South Carolina",
      site:null, img:"img/animals/pelagornis.svg", sources:[67, 68] }
  ],
  now: [
    { genus:"Apteryx", group:"kiwi", habitat:"land",
      environment:"Flightless and mostly nocturnal, it rests in burrows and hollow logs; on Stewart Island some birds feed by day.",
      size:"About 45 centimetres long and 2.4 to 3.1 kilograms, the size of a domestic hen.",
      matters:"Flightless ratites were long explained as one family split apart by the breakup of Gondwana; DNA from Madagascar's extinct elephant birds shows they are the kiwi's closest relatives, so the ancestors flew between landmasses and lost flight afterwards.",
      plate:"AUS", lon:167.9, lat:-47.0, place:"Rakiura (Stewart Island), New Zealand",
      site:null, img:"img/animals/apteryx.svg", sources:[69, 70, 71] },
    { genus:"Dromiciops", group:"monito del monte, a marsupial", habitat:"land",
      environment:"Cool temperate rainforest of southern Chile and neighbouring Argentina, in trees up to 30 metres high; it hibernates through half the year.",
      size:"About 11 centimetres from snout to rump and 20 to 30 grams, the weight of a mouse.",
      matters:"The only living member of its order and the closest living relative of the Australian marsupials, a trace of the route marsupials took from South America across Antarctica to Australia.",
      plate:"SAM", lon:-72.5, lat:-41.5, place:"Valdivian rainforest, Los Ríos and Los Lagos, Chile",
      site:"Valdivian rainforest", img:"img/animals/dromiciops.svg", sources:[72, 73] },
    { genus:"Lemur", group:"ring-tailed lemur", habitat:"land",
      environment:"Gallery forest, dry thicket and spiny desert in the south and south-west of Madagascar.",
      size:"2.2 to 2.7 kilograms, lighter than most house cats.",
      matters:"Lemurs descend from ancestors that crossed from Africa 60 to 50 million years ago, probably rafted on currents that then ran east toward Madagascar; the currents later reversed, and no land mammal has made the crossing since the early Miocene.",
      plate:"MAD", lon:46.9, lat:-21.9, place:"Anja Community Reserve, near Ambalavao, Madagascar",
      site:null, img:"img/animals/lemur.svg", sources:[74, 75, 76] },
    { genus:"Latimeria", group:"coelacanth", habitat:"marine",
      environment:"Caves in submarine canyons about 100 metres down, off the coast of KwaZulu-Natal.",
      size:"Males rarely pass 1.5 metres; the largest fish on record measure 1.8 to 1.9 metres, the height of a tall person, and weigh up to 98 kilograms.",
      matters:"Coelacanths were thought to have died out at the end of the Cretaceous, 66 million years ago, until a trawler brought one up off East London in December 1938.",
      plate:"AFR", lon:32.7, lat:-27.5, place:"Jesser Canyon, Sodwana Bay, iSimangaliso Wetland Park, South Africa",
      site:null, img:"img/animals/latimeria.svg", sources:[77, 78] },
    { genus:"Sphenodon", group:"tuatara", habitat:"land",
      environment:"Rodent-free islands off New Zealand, in burrows among seabird colonies; it stays active in weather too cool for most reptiles.",
      size:"Adult males are about half a metre long and weigh up to 1.5 kilograms, which makes it New Zealand's largest reptile.",
      matters:"The last survivor of an order of reptiles once widespread across Gondwana; its lineage split from lizards and snakes about 250 million years ago.",
      plate:"AUS", lon:174.0, lat:-40.67, place:"Takapourewa (Stephens Island), Marlborough Sounds, New Zealand",
      site:null, img:"img/animals/sphenodon.svg", sources:[79, 80] },
    { genus:"Anser", group:"bar-headed goose", habitat:"air",
      environment:"It winters at sea level on Indian wetlands and spends the summer on the lakes of central Asia, crossing the Himalaya twice a year.",
      size:"About 2.4 kilograms, with a wingspan near 1.45 metres.",
      matters:"Its migration crosses the mountains that India raised: tracked birds climb 4,000 to 6,000 metres in seven to eight hours, and one was recorded at 7,290 metres.",
      plate:"IND", lon:85.3, lat:19.7, place:"Chilika Lake, Odisha, India",
      site:null, img:"img/animals/anser.svg", sources:[81, 82] },
    { genus:"Neoceratodus", group:"lungfish", habitat:"freshwater",
      environment:"Still or slow-flowing pools in the rivers of south-eastern Queensland, where it gulps air with its single lung when the water turns stagnant.",
      size:"Up to about 1.5 metres long and over 40 kilograms.",
      matters:"Living lungfish survive on three continents only, one genus each in Australia, South America and Africa, although Mesozoic fossils of this group turn up almost worldwide; they are also thought to be the closest living relatives of four-limbed animals.",
      plate:"AUS", lon:151.9, lat:-25.2, place:"Burnett River, Queensland, Australia",
      site:null, img:"img/animals/neoceratodus.svg", sources:[83, 84] },
    { genus:"Pusa", group:"Baikal seal", habitat:"freshwater",
      environment:"Lake Baikal, a rift lake about 25 million years old and more than 1,600 metres deep, where the seals breed on the winter ice.",
      size:"Up to 1.65 metres long and 130 kilograms.",
      matters:"The only seal that lives wholly in fresh water, more than 3,000 kilometres from the Arctic Ocean its ancestors came from; estimates of when they arrived range from 0.4 to 3 million years ago.",
      plate:"SIB", lon:108.0, lat:53.5, place:"Lake Baikal, Siberia",
      site:null, img:"img/animals/pusa.svg", sources:[85, 86, 87] },
    { genus:"Ornithorhynchus", group:"platypus", habitat:"freshwater",
      environment:"Rivers and streams of eastern Australia, from tropical Queensland to the cold highlands of the Australian Alps and Tasmania.",
      size:"Males are 40 to 63 centimetres long and weigh 0.8 to 3 kilograms; females are smaller.",
      matters:"Egg-laying mammals arose in the Australian and Antarctic part of Gondwana, and a platypus tooth 61 to 63 million years old from Patagonia is the only trace of the family outside Australia.",
      plate:"AUS", lon:148.4, lat:-36.4, place:"Streams of the Australian Alps, New South Wales",
      site:null, img:"img/animals/ornithorhynchus.svg", sources:[88, 89] },
    { genus:"Dasypus", group:"nine-banded armadillo", habitat:"land",
      environment:"Warm-temperate and subtropical country from Texas across the Gulf and Atlantic coastal plains, with the range still spreading north.",
      size:"Body 38 to 43 centimetres with a tail nearly as long, and 3.6 to 7.7 kilograms, about the size of a cat.",
      matters:"Armadillos came from South America: Dasypus walked north about 2.4 million years ago, after the Isthmus of Panama joined the continents around 2.8 million years ago, and the living species was first recorded in Texas in the 1840s.",
      plate:"NAM", lon:-98.2, lat:26.2, place:"Rio Grande valley, Texas",
      site:null, img:"img/animals/dasypus.svg", sources:[90, 91, 92, 93, 94] }
  ]
};
