/* ===================== the timeline =====================
   plates: [ centre longitude, centre latitude, spin (clockwise, degrees) ]
   Sites are pinned to a plate at modern lon/lat and travel with it.        */

const PERIODS = [
{
  id:"cam", name:"Cambrian", ma:510, span:"538–485 million years ago",
  colour:"#7FA056", accent:"#9CBE72", view:[-30,-12],
  headline:"Gondwana is still being welded together",
  body:[
    "The continents are scattered and unfamiliar. Laurentia — the old core of North America — sits on the equator, turned about a quarter turn from the way it faces today, with its present-day east coast looking south into the Iapetus Ocean. Baltica and Siberia are separate islands.",
    "Gondwana is assembling out of Africa, South America, India, Australia and Antarctica, and the pieces that will become Australia and East Antarctica are in the tropics. Warm shallow seas cover most continental interiors, and animals with hard parts have just appeared in them.",
    "Land is empty. Not sparse — empty. There are no plants, no soil in the modern sense, and nothing taller than a bacterial crust."
  ],
  facts:[
    ["North pole","Open ocean, as it will be for most of the next 450 million years"],
    ["South pole","Near the edge of Gondwana, around what is now West Africa and northern Brazil"],
    ["Sea level","Very high; continental interiors flooded"],
    ["Land plants","None"]
  ],
    plates:{ NAM:[27.9,-2,34.2], EUR:[66.3,-54.7,19.9], SIB:[-50.7,14,68], CHI:[576.7,-10,75.1],
           IND:[187.9,-40.8,-28.4], AFR:[240.2,-77.7,58.7], SAM:[-81.5,-46.9,86.4],
           AUS:[187.2,-13.2,-89.6], ANT:[-140.7,-32.7,41.1], MAD:[189.1,-52.1,20.2] },
  ice:[],
  sites:[
    { plate:"NAM", lon:-116.5, lat:51.4, cat:"fossil",
      title:"Burgess Shale", sub:"508 million years old",
      body:"Mud slid off the edge of a tropical carbonate platform and buried soft-bodied animals so fast that eyes, guts and gill filaments survived. Anomalocaris, Opabinia and Hallucigenia come from here, and they record a point when the basic body plans of animals were still being tried out.",
      then:{ where:"Equatorial sea floor", icon:"reef",
             text:"A steep drowned reef wall in warm water a few degrees from the equator." },
      now:{ where:"Yoho National Park, British Columbia", icon:"conifer",
            text:"The same rock now sits 2,300 metres up a ridge in the Canadian Rockies, in subalpine forest of Engelmann spruce and subalpine fir, under snow much of the year." } },
    { plate:"CHI", lon:102.6, lat:24.7, cat:"fossil",
      title:"Chengjiang", sub:"518 million years old",
      body:"Ten million years older than the Burgess Shale and preserved on a separate small continent drifting in the eastern ocean. Its fossils include Myllokunmingia and Haikouichthys — finger-length swimmers with a stiffening rod down the back, which puts them close to the ancestry of all vertebrates.",
      then:{ where:"Shallow tropical shelf", icon:"sea",
             text:"A quiet muddy sea floor on a small isolated block, repeatedly smothered by storm mud." },
      now:{ where:"Yunnan, China", icon:"broadleaf",
            text:"Red-earth hills above Fuxian Lake, subtropical and humid, with evergreen oak, pine and terraced farmland." } },
    { plate:"ANT", lon:160, lat:-84, cat:"fossil",
      title:"The first reefs, in Antarctica", sub:"Shackleton Limestone",
      body:"Archaeocyaths — cup-shaped sponge relatives — built the first animal reefs, and some of the best preserved are in the Transantarctic Mountains. Reef builders need warm, clear, shallow water, which is direct evidence of where this rock formed.",
      then:{ where:"Tropical shallow sea", icon:"reef",
             text:"Clear warm water with reef mounds a few metres high, inside the tropics." },
      now:{ where:"Transantarctic Mountains", icon:"ice",
            text:"Exposed rock and ice, roughly 400 km from the South Pole. Antarctica has two native flowering plants in total, both on the peninsula, and neither grows anywhere near here." } },
    { plate:"AUS", lon:137.5, lat:-35.7, cat:"fossil",
      title:"Emu Bay Shale", sub:"Kangaroo Island",
      body:"One of only a handful of places where Cambrian eyes are preserved in detail. The compound eyes found here belong to Anomalocaris and hold more than 16,000 lenses each, which says that fast visual hunting was already underway.",
      then:{ where:"Tropical Gondwanan margin", icon:"sea",
             text:"A shallow basin on the warm northern edge of Gondwana." },
      now:{ where:"Kangaroo Island, South Australia", icon:"scrub",
            text:"Cliffs above a cold southern-ocean beach, with mallee eucalypt scrub and coastal heath behind them." } },
    { plate:"AFR", lon:24, lat:-12, cat:"forest",
      title:"An empty continent", sub:"What was growing on land",
      body:"Nothing, in any way we would recognise. No roots meant no soil and no riverbanks, so rivers spread into wide braided sheets across bare rock and sand. Damp hollows held crusts of cyanobacteria and green algae, and that was the whole of the land flora.",
      then:{ where:"Bare rock across every continent", icon:"microbe",
             text:"Coloured microbial films in wet ground; everything else scoured stone." },
      now:{ where:"Central Africa", icon:"broadleaf",
            text:"The same ground carries the Congo rainforest, with a canopy 40 metres up and about 10,000 plant species." } }
  ]
},
{
  id:"ord", name:"Ordovician", ma:445, span:"485–443 million years ago",
  colour:"#009270", accent:"#2BB894", view:[-20,-40],
  headline:"An ice sheet grows over the Sahara",
  body:[
    "Gondwana has drifted over the South Pole, and the part of it now sitting on the pole is northwest Africa. An ice sheet spreads across what will become Algeria, Libya, Mauritania and Niger, and the grooves its base cut into the bedrock are still visible in the desert.",
    "That ice locks up seawater and drops sea level sharply. The shallow seas covering the continents drain, and roughly 85 percent of marine species die — the first of the five great mass extinctions, and by species count the second worst.",
    "Meanwhile something small is happening on land. The first plants, liverwort-grade and only millimetres tall, have taken hold in damp ground."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Under what is now the central Sahara"],
    ["Ice","A continental ice sheet across northwest Gondwana"],
    ["Land plants","Millimetre-scale, liverwort-like, in wet ground only"]
  ],
    plates:{ NAM:[-71.5,-8.1,-11.9], EUR:[-14.9,-48.4,11.9], SIB:[-78.8,16,72],
           CHI:[512.4,-13.6,28], IND:[206.5,-31,32], AFR:[232.8,-71.1,122.3],
           SAM:[-72.4,-47.9,125.7], AUS:[206.7,-3.4,-67.6], ANT:[-124.4,-25.2,99.7],
           MAD:[206.9,-42.4,110.3] },
  ice:[{ plate:"AFR", lon:2, lat:24, r:30 }],
  sites:[
    { plate:"AFR", lon:3, lat:26, cat:"ice",
      title:"The Saharan ice sheet", sub:"Hirnantian glaciation",
      body:"Glacial pavements, dropstones and tillites run in a belt across North Africa. In parts of southern Algeria you can stand on bedrock scored by parallel grooves pointing away from a polar ice dome, in a landscape where it now rains a few millimetres a year.",
      then:{ where:"Polar ice cap", icon:"ice",
             text:"Kilometres of ice, grinding north from a dome centred close to the pole." },
      now:{ where:"Algeria, Libya, Mauritania", icon:"dune",
            text:"Hyper-arid desert. Date palms in oases, acacia and tamarisk along dry watercourses." } },
    { plate:"NAM", lon:-73.8, lat:42.8, cat:"event",
      title:"The first Appalachian mountains", sub:"Taconic orogeny",
      body:"A chain of volcanic islands in the Iapetus Ocean ran into the eastern edge of Laurentia and was scraped onto it. This is the first of three collisions that will build the Appalachians, and the deformed rock it produced is what you walk on in the Taconic Range and the Berkshires.",
      then:{ where:"Equatorial island-arc collision", icon:"volcano",
             text:"Volcanic islands crumpling against a tropical carbonate shelf, shedding mud westward into a deepening trough." },
      now:{ where:"Eastern New York and western Massachusetts", icon:"broadleaf",
            text:"Worn-down ridges under northern hardwood forest — sugar maple, American beech, yellow birch — with hemlock in the ravines." } },
    { plate:"AFR", lon:-6, lat:31, cat:"fossil",
      title:"Fezouata Biota", sub:"Early in the period, about 478 Ma",
      body:"A soft-bodied fauna preserved in cold, high-latitude water, which is unusual — most such deposits are tropical. It shows Cambrian-style animals, including giant filter-feeding relatives of Anomalocaris two metres long, still going strong tens of millions of years after they were thought to have died out.",
      then:{ where:"Cold shelf sea, far south", icon:"sea",
             text:"Storm-swept muddy shelf at high southern latitude, on the margin of Gondwana." },
      now:{ where:"Zagora, Morocco", icon:"dune",
            text:"Stony desert on the edge of the Sahara, with date palm groves along the Draa valley." } },
    { plate:"AFR", lon:56, lat:21, cat:"forest",
      title:"The first land plants", sub:"Cryptospores in Oman",
      body:"Tough, four-part spore clusters turn up in Ordovician rock long before any recognisable plant fossil. They match what liverworts produce, and they are the earliest firm evidence of plants living out of water. Nothing here is taller than a coin is wide.",
      then:{ where:"Damp ground, Gondwanan margin", icon:"moss",
             text:"Low mats hugging wet sand and rock, with no roots and no vascular tissue." },
      now:{ where:"Oman", icon:"dune",
            text:"Desert and gravel plain, with frankincense trees on the escarpments and a narrow monsoon-green belt in the far south." } }
  ]
},
{
  id:"sil", name:"Silurian", ma:425, span:"443–419 million years ago",
  colour:"#B3E1B6", accent:"#B3E1B6", view:[-10,-20],
  headline:"Plants get stems, and continents start to collide",
  body:[
    "The ice melts, sea level rises, and reefs rebuild across the tropics. Baltica is closing in on Laurentia and the Iapetus Ocean is narrowing fast; the collision is already throwing up the Caledonian mountains along what will become Scotland, Norway and eastern Greenland.",
    "On land, Cooksonia appears: a few centimetres tall, leafless, just a forking green stem with a spore capsule on each tip. It is the first plant with vascular tissue — internal plumbing — and that single innovation is what eventually makes trees possible.",
    "The first animals with jaws are in the water, and millipedes and early arachnids are out of it."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Over Gondwana, near what is now southern Africa"],
    ["Mountains rising","The Caledonides, along the closing Iapetus suture"],
    ["Tallest plant","A few centimetres"]
  ],
    plates:{ NAM:[-38.9,-13,-18.8], EUR:[10.4,-34.4,28.4], SIB:[-63.9,22,62], CHI:[358.8,-16,38],
           IND:[199.7,-37.7,0.7], AFR:[237.3,-76.9,95], SAM:[-71.5,-48.9,108.4],
           AUS:[200.2,-10.1,-73.3], ANT:[-129.3,-31.1,77.4], MAD:[200,-49.1,72.7] },
  ice:[],
  sites:[
    { plate:"EUR", lon:-2.9, lat:52, cat:"forest",
      title:"Cooksonia", sub:"The first vascular plant",
      body:"Found in Welsh and Irish rock, and no bigger than a thumbnail. A bare green stem forks once or twice and ends in a rounded spore capsule, with a thin strand of water-conducting cells running up the middle. Everything from a fern to a redwood is built on that strand.",
      then:{ where:"Wet coastal flats, Avalonia", icon:"moss",
             text:"Patches of low forking stems on mud and sand beside the sea, with no leaves and no roots." },
      now:{ where:"Welsh Borders", icon:"broadleaf",
            text:"Sheep pasture, hedgerow, and oak and ash woodland on the old red hills." } },
    { plate:"EUR", lon:17, lat:57.5, cat:"event",
      title:"The Caledonian collision", sub:"Iapetus closes",
      body:"Baltica swings into Laurentia and the ocean between them is squeezed shut. The resulting mountain belt was Himalayan in scale. Its eroded roots are now split across four places that used to be continuous: the Scottish Highlands, the Norwegian mountains, eastern Greenland, and the northern Appalachians.",
      then:{ where:"A continental collision at about 30° south", icon:"volcano",
             text:"A rising mountain chain along a suture, shedding sand into basins on either side." },
      now:{ where:"Scandinavia and Scotland", icon:"taiga",
            text:"Worn plateaus and fjords under spruce, pine and birch in Norway; heather moor and remnant Caledonian pinewood in Scotland." } },
    { plate:"AUS", lon:148, lat:-34, cat:"fossil",
      title:"Reefs return", sub:"After the Ordovician extinction",
      body:"Tabulate and rugose corals and stromatoporoid sponges rebuild tropical reef systems, and Silurian reef limestone is quarried today from Gotland to New South Wales. Sea scorpions — eurypterids, some over two metres — are the largest arthropods that have ever lived.",
      then:{ where:"Warm shelf sea", icon:"reef",
             text:"Coral and sponge reef mounds in clear, shallow, tropical water." },
      now:{ where:"New South Wales", icon:"scrub",
            text:"Limestone hills and caves inland of the Great Dividing Range, under dry eucalypt woodland." } }
  ]
},
{
  id:"dev", name:"Devonian", ma:385, span:"419–359 million years ago",
  colour:"#CB8C37", accent:"#DFA359", view:[-15,-8],
  headline:"Forests appear, and fish start walking",
  body:[
    "Laurentia and Baltica are now one continent, Laurussia, straddling the equator. Its interior is a hot dry basin filling with rust-red sand — the Old Red Sandstone, which is why so much of Britain, Norway and the Catskills is built of red rock.",
    "Plants solve the height problem. Archaeopteris grows woody trunks and real roots, and by the late Devonian there are forests thirty metres tall. Roots crack rock into soil, soil washes nutrients into rivers, rivers feed algal blooms, and the resulting oxygen crashes help drive a mass extinction in the sea.",
    "In the shallows, lobe-finned fish with wrists and ribs are starting to prop themselves up in the weeds."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Over Gondwana, near what is now Argentina and southern Africa"],
    ["New that period","Wood, roots, seeds, soil and forests"],
    ["Atmosphere","Carbon dioxide falling steeply as forests spread"]
  ],
    plates:{ NAM:[6.2,1,33.2], EUR:[41.8,-16.3,-9], SIB:[62.8,28,40], CHI:[225.3,-14,34],
           IND:[185.6,-47,-28.6], AFR:[116.2,-88.7,9], SAM:[-61.7,-57.1,53],
           AUS:[192.7,-20,-92.2], ANT:[-136.6,-44.5,3.3], MAD:[180.9,-58.1,-20] },
  ice:[],
  sites:[
    { plate:"NAM", lon:-74.4, lat:42.4, cat:"forest",
      title:"The Gilboa forest", sub:"386 million years old",
      body:"Quarrying for a dam in 1920 turned up dozens of fossil tree stumps standing where they grew. They belong to Eospermatopteris, a tree the shape of a giant celery stalk with a flared base and a crown of branches instead of leaves. A nearby site at Cairo preserves the root systems of Archaeopteris, spreading more than eleven metres.",
      then:{ where:"Tropical river plain, about 15° south", icon:"fern",
             text:"A humid floodplain forest of tall branching trunks, repeatedly buried by floods." },
      now:{ where:"Schoharie County, New York", icon:"broadleaf",
            text:"Catskill hill country under maple, beech and hemlock. Some of the fossil stumps are set up in the village of Gilboa." } },
    { plate:"EUR", lon:-2.8, lat:57.4, cat:"fossil",
      title:"Rhynie chert", sub:"407 million years old",
      body:"A hot spring flooded a marshy plain with silica-rich water and turned an entire ecosystem to glass, cell by cell. You can see individual plant cells, fungal threads inside roots, springtails, mites, and the oldest known insect. It is the closest thing we have to a photograph of an early land ecosystem.",
      then:{ where:"Hot springs on an arid rift floor", icon:"moss",
             text:"Low tufted plants around silica-crusted pools, in a dry equatorial basin." },
      now:{ where:"Aberdeenshire, Scotland", icon:"grass",
            text:"Flat farmland — barley, grass leys and a scatter of conifer shelterbelts. There is nothing to see above ground." } },
    { plate:"NAM", lon:-83, lat:77, cat:"fossil",
      title:"Tiktaalik", sub:"375 million years old",
      body:"A metre-and-a-half predator with gills, scales and fins, but also a neck, ribs strong enough for gravity, and a shoulder, elbow and wrist inside its front fin. It lived in shallow weed-choked streams, and it sits about as close to the fish-to-tetrapod transition as any fossil we have.",
      then:{ where:"Tropical river delta near the equator", icon:"swamp",
             text:"Warm, shallow, seasonally drying channels choked with plants." },
      now:{ where:"Ellesmere Island, Nunavut", icon:"tundra",
            text:"High Arctic polar desert at 77° north. Purple saxifrage, Arctic willow a few centimetres tall, and months of darkness." } },
    { plate:"AFR", lon:26, lat:-33, cat:"fossil",
      title:"Tetrapods outside the tropics", sub:"Waterloo Farm",
      body:"Tetrapod fossils from South Africa show that four-limbed animals were not restricted to the tropics — these lived at high southern latitudes in cold water with short winter days. It undercuts the old picture of tetrapods evolving only in warm equatorial swamps.",
      then:{ where:"Cold estuary, about 55° south", icon:"sea",
             text:"A cold tidal estuary a long way south of the Devonian tropics." },
      now:{ where:"Eastern Cape, South Africa", icon:"scrub",
            text:"Thicket and grassland near Makhanda, warm-temperate, with spekboom and aloes on the slopes." } }
  ]
},
{
  id:"car", name:"Carboniferous", ma:310, span:"359–299 million years ago",
  colour:"#67A599", accent:"#7FBFB2", view:[-5,-14],
  headline:"Coal swamps on the equator, ice at the pole",
  body:[
    "Laurussia sits squarely on the equator and is covered in wet forest. The trees are lycopsids — Lepidodendron and Sigillaria — up to fifty metres tall, with green photosynthetic bark and shallow forked anchors instead of proper roots. They grow fast, fall, and pile up in stagnant water.",
    "That peat is the coal that later fuelled the industrial revolution. Nearly every major coal field in the eastern United States, Britain, Belgium, Germany and Poland is the compressed floor of these swamps.",
    "At the same time Gondwana is sliding over the South Pole and growing an ice sheet that will last some seventy million years. The planet has a hot wet equator and a frozen southern hemisphere at once. Oxygen reaches about 30 percent of the atmosphere, roughly half again today's level, and insects get enormous."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Over southern Gondwana, under a long-lived ice sheet"],
    ["Oxygen","Around 30 percent, the highest in Earth's history"],
    ["Largest insect","Meganeura, a dragonfly relative with a 70 cm wingspan"]
  ],
    plates:{ NAM:[-10.7,14.4,8], EUR:[29.1,9.1,-16.3], SIB:[128.2,34.3,35.1], CHI:[240,0.4,8],
           IND:[52.4,-64.7,28.3], AFR:[2.4,-34.4,17.5], SAM:[-38.6,-31.9,2.5],
           AUS:[121.6,-65.6,-83.3], ANT:[-30,-78.2,-24], MAD:[34.1,-57.4,1.2] },
  ice:[{ plate:"ANT", lon:0, lat:-83, r:26 },{ plate:"AFR", lon:26, lat:-30, r:20 }],
  sites:[
    { plate:"NAM", lon:-64.4, lat:45.7, cat:"forest",
      title:"Joggins Fossil Cliffs", sub:"Nova Scotia",
      body:"Tides in the Bay of Fundy strip the cliff face back every year and expose fossil lycopsid trunks still standing upright in the rock, buried where they grew. Hollow stumps acted as pit traps, and one of them contained Hylonomus, among the earliest known reptiles.",
      then:{ where:"Equatorial coastal swamp", icon:"lycopod",
             text:"A subsiding delta of peat forest, flooded and reburied again and again." },
      now:{ where:"Bay of Fundy, Nova Scotia", icon:"conifer",
            text:"Red sea cliffs under the world's highest tides, backed by Acadian forest of red spruce, balsam fir, maple and birch." } },
    { plate:"NAM", lon:-88.1, lat:41.4, cat:"fossil",
      title:"Mazon Creek", sub:"Illinois",
      body:"Animals that fell into a muddy river delta were sealed inside iron carbonate nodules that split open along the fossil. The result is a rare record of soft-bodied swamp life — jellyfish, worms, insects — including the Tully monster, an animal so strange that palaeontologists still argue about which part of the animal kingdom it belongs to.",
      then:{ where:"Equatorial delta", icon:"swamp",
             text:"Brackish channels and mudflats at the edge of a coal forest, on the equator." },
      now:{ where:"Grundy County, Illinois", icon:"grass",
            text:"Strip-mine spoil heaps and reclaimed prairie, now mostly maize, soybean and tallgrass restoration." } },
    { plate:"EUR", lon:-1.5, lat:53.5, cat:"forest",
      title:"The coal measures", sub:"Northern England",
      body:"Cyclic layers of sandstone, shale, seatearth and coal, repeated dozens of times as sea level rose and fell with the southern ice sheet. Each coal seam is a drowned forest. The whole industrial geography of Britain sits on top of them.",
      then:{ where:"Equatorial peat forest", icon:"lycopod",
             text:"Fifty-metre lycopsid trees with green trunks, over an understorey of tree ferns and horsetails." },
      now:{ where:"Yorkshire and the East Midlands", icon:"grass",
            text:"Farmland and former pit villages. Oak, ash and sycamore in the hedges; the mines are closed and the spoil heaps are grassed over." } },
    { plate:"AFR", lon:28, lat:-27, cat:"ice",
      title:"The Dwyka glaciation", sub:"Karoo ice age",
      body:"Under the Karoo's rock lies the Dwyka tillite: unsorted rubble dumped by an ice sheet, resting on bedrock polished and scratched by ice. The same glacial layer appears in Brazil, India, Australia and Antarctica, and matching it across those continents was a central piece of evidence for continental drift.",
      then:{ where:"Under a polar ice sheet", icon:"ice",
             text:"Continental ice, thick enough to grind and polish the bedrock beneath it." },
      now:{ where:"Northern Cape and Free State, South Africa", icon:"scrub",
            text:"Semi-arid Karoo, hot and thorny, with dwarf shrubs and sweet grasses on the plains." } },
    { plate:"EUR", lon:3, lat:49.5, cat:"fossil",
      title:"Giant insects", sub:"Meganeura",
      body:"Insects breathe by diffusion through tubes, so body size is limited by how much oxygen the air holds. At roughly 30 percent oxygen that ceiling lifts. Meganeura had a wingspan of about 70 centimetres, and millipede relatives in the genus Arthropleura reached two and a half metres.",
      then:{ where:"Oxygen-rich equatorial forest", icon:"fern",
             text:"Humid forest floor and standing water, with no flying vertebrates yet to compete with." },
      now:{ where:"Northern France and Belgium", icon:"broadleaf",
            text:"Beech and oak woodland, arable plain, and the old coal basin of the Nord." } }
  ]
},
{
  id:"per", name:"Permian", ma:260, span:"299–252 million years ago",
  colour:"#F04028", accent:"#F0674F", view:[10,-10],
  headline:"One continent, from pole to pole",
  body:[
    "Pangaea is assembled. You could walk from the north of Siberia to the south of Antarctica without crossing salt water, and a single ocean, Panthalassa, covers the rest of the planet. Only the Chinese blocks are still out on their own in the Tethys.",
    "A continent that big generates a monsoon that never reaches its middle. The interior is desert on a scale the world has not had since — sand seas thousands of kilometres across, now preserved as the red sandstones of the American southwest and northern Europe.",
    "At the southern end, Glossopteris forests cover Gondwana, including land within a few degrees of the pole. Then, at the very end of the period, the Siberian Traps erupt, and about 80 to 90 percent of all species disappear."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Over Antarctica and southern Australia"],
    ["Climate","A supercontinental monsoon with a vast dead-dry interior"],
    ["Ending","The largest mass extinction known, 252 million years ago"]
  ],
    plates:{ NAM:[-23.1,19.3,0], EUR:[19,26.1,-13.8], SIB:[18.5,66.2,7.5], CHI:[283.7,2,39],
           IND:[48.1,-49.5,32.1], AFR:[3.3,-24.9,5.6], SAM:[-35,-32.2,-18.6],
           AUS:[93.5,-56.2,-85.3], ANT:[13.8,-70.4,-42.1], MAD:[34.5,-43.1,-7.6] },
  ice:[],
  sites:[
    { plate:"ANT", lon:162, lat:-85, cat:"forest",
      title:"Polar forests in Antarctica", sub:"Glossopteris",
      body:"Fossil tree trunks and leaf mats occur in the Transantarctic Mountains at latitudes within about 20° of the South Pole. Glossopteris was deciduous — it dropped its leaves for the polar winter, and its growth rings are wide and abrupt, the signature of a plant racing through a short intense summer.",
      then:{ where:"About 20° from the South Pole", icon:"cycad",
             text:"Seasonal forest of tongue-leaved seed plants on a river plain, dark for months at a time." },
      now:{ where:"Transantarctic Mountains", icon:"ice",
            text:"Rock, ice and wind. The fossil wood weathers out of cliffs that sit above a two-kilometre ice sheet." } },
    { plate:"AFR", lon:24, lat:-32, cat:"fossil",
      title:"The Karoo Basin", sub:"South Africa",
      body:"The thickest continuous record anywhere of life on land through the end-Permian extinction. Below the boundary the rock is full of dicynodonts and other therapsids — mammal ancestors with differentiated teeth. Above it, for millions of years, almost the only large animal is the stocky survivor Lystrosaurus.",
      then:{ where:"Cool temperate river plain, about 60° south", icon:"cycad",
             text:"Broad meandering rivers across a Glossopteris floodplain, drying out as the extinction approaches." },
      now:{ where:"Great Karoo, South Africa", icon:"scrub",
            text:"Semi-desert of low shrubs and flat-topped hills, hot by day and cold at night, grazed by merino sheep." } },
    { plate:"SIB", lon:94, lat:69, cat:"event",
      title:"The Siberian Traps", sub:"252 million years ago",
      body:"Lava covered an area the size of Western Europe, but the worse problem was what it burned through: a thick basin of coal, salt and organic shale. The resulting carbon dioxide, methane and halogens acidified the oceans, stripped ozone and drove sustained global warming, and the extinction followed.",
      then:{ where:"Flood basalt province", icon:"volcano",
             text:"Repeated fissure eruptions across northern Pangaea over roughly a million years." },
      now:{ where:"Putorana Plateau, Siberia", icon:"taiga",
            text:"A stepped basalt plateau cut by canyons and waterfalls, under open Dahurian larch forest on permafrost." } },
    { plate:"NAM", lon:-110, lat:38, cat:"event",
      title:"The great sand sea", sub:"Pangaea's interior",
      body:"The Coconino and Cedar Mesa sandstones are lithified dunes, with cross-bedding that records wind directions and trackways of small reptiles running up dune faces. Equivalent dune fields of the same age lie beneath the North Sea and much of northern Germany.",
      then:{ where:"Continental desert", icon:"dune",
             text:"A dune field of continental scale, thousands of kilometres from any coast." },
      now:{ where:"Colorado Plateau", icon:"conifer",
            text:"High desert of piñon pine, juniper and sagebrush, with the old dunes standing as the pale cliffs of Zion and the Grand Canyon's upper walls." } },
    { plate:"AUS", lon:150.5, lat:-32.5, cat:"forest",
      title:"Gondwanan coal", sub:"Sydney Basin",
      body:"Glossopteris peat built coal in Australia, India, South Africa, South America and Antarctica — all of it at high southern latitudes, all of it in the same distinctive flora. The match was one of the original arguments for a single southern supercontinent.",
      then:{ where:"Cool temperate swamp, about 50° south", icon:"cycad",
             text:"Boggy forest of Glossopteris with a strongly seasonal, low-angle light regime." },
      now:{ where:"Hunter Valley, New South Wales", icon:"scrub",
            text:"Open eucalypt woodland, vineyards and large open-cut coal mines working the same Permian seams." } }
  ]
},
{
  id:"tri", name:"Triassic", ma:220, span:"252–201 million years ago",
  colour:"#812B92", accent:"#B061C6", view:[5,0],
  headline:"Life rebuilds, and the first dinosaurs appear",
  body:[
    "Pangaea is still whole but has begun to pull apart along a line that will become the Atlantic. Rift valleys open through what is now the Connecticut Valley, New Jersey and Morocco, fill with lakes, and then fill with lava.",
    "Recovery from the end-Permian extinction takes several million years. When ecosystems do rebuild, the winners are new: the first turtles, the first mammals, the first pterosaurs, and — about 231 million years ago, in what is now Argentina — the first dinosaurs, which spend the whole period as a minor group.",
    "There is no ice at either pole and no grass anywhere. Conifers, cycads, ginkgos and ferns make up the vegetation."
  ],
  facts:[
    ["North pole","Open ocean"],
    ["South pole","Ocean off Antarctica, with no ice sheet"],
    ["First appearing","Dinosaurs, mammals, pterosaurs, turtles, crocodile ancestors"],
    ["Ending","Extinction at 201 Ma as Pangaea's rifts erupt"]
  ],
    plates:{ NAM:[-31.5,24,-27.7], EUR:[8,28.1,19.9], SIB:[45.2,59.1,29.8], CHI:[205,12,24],
           IND:[48.6,-50.2,34.9], AFR:[4.1,-24.9,8], SAM:[-34.2,-31.6,-15.2],
           AUS:[94.7,-57.1,-80.5], ANT:[12.5,-70.5,-35.8], MAD:[35,-43.6,-3.4] },
  ice:[],
  sites:[
    { plate:"SAM", lon:-68, lat:-30.2, cat:"fossil",
      title:"Ischigualasto", sub:"231 million years old",
      body:"A sequence of dated volcanic ash layers running through river sediments, which is why the earliest dinosaurs can be pinned down so precisely here. Eoraptor and Herrerasaurus come from this valley — bipedal, a metre or three long, and thoroughly outnumbered by crocodile-line reptiles they shared the plain with.",
      then:{ where:"Seasonal river plain, about 45° south", icon:"fern",
             text:"Volcanic ash falling on a forested floodplain with a strong wet and dry cycle." },
      now:{ where:"Valle de la Luna, San Juan, Argentina", icon:"scrub",
            text:"Wind-carved desert badlands in the Andean rain shadow, with sparse monte scrub of creosote bush and cactus." } },
    { plate:"NAM", lon:-109.8, lat:34.9, cat:"forest",
      title:"Petrified Forest", sub:"Chinle Formation, Arizona",
      body:"Whole conifer trunks up to fifty metres long, silicified log by log, with the cell walls replaced by quartz coloured by iron and manganese. The main tree, Araucarioxylon arizonicum, is a relative of the monkey puzzle and the Norfolk Island pine.",
      then:{ where:"Tropical river plain, about 15° north", icon:"conifer",
             text:"Big rivers flowing north-west across a warm humid lowland, carrying logs into sandbanks." },
      now:{ where:"Painted Desert, Arizona", icon:"grass",
            text:"Cold semi-desert at 1,700 m. Blue grama, saltbush and rabbitbrush, and no trees at all for a hundred kilometres." } },
    { plate:"NAM", lon:-74.5, lat:40.8, cat:"event",
      title:"Pangaea starts to split", sub:"Newark rift basins",
      body:"A chain of rift valleys opened from the Carolinas to Nova Scotia, filled with deep lakes whose sediments record cycles driven by the Earth's orbit. Magma pushed sideways into those sediments and cooled into a sheet of dolerite — the Palisades, the cliff wall along the Hudson opposite Manhattan.",
      then:{ where:"Continental rift, about 15° north", icon:"volcano",
             text:"Deep lakes between fault scarps, subtropical and strongly seasonal, with lava sheets spreading through." },
      now:{ where:"Hudson Valley and New Jersey", icon:"city",
            text:"The rift's shoulder is the Palisades cliff; its floor holds the New Jersey suburbs, under oak, tulip poplar and maple." } },
    { plate:"AFR", lon:-7, lat:31.5, cat:"event",
      title:"The largest lava province on Earth", sub:"CAMP, 201 Ma",
      body:"When the rift finally tore, it erupted across four modern continents at once — Morocco, Iberia, eastern North America and Brazil. It is the most extensive flood basalt province known, and its carbon dioxide release lines up with the end-Triassic extinction that cleared the way for dinosaurs to dominate.",
      then:{ where:"Central Pangaea rift", icon:"volcano",
             text:"Fissure eruptions along the opening seam between Africa and North America." },
      now:{ where:"High Atlas, Morocco", icon:"scrub",
            text:"Basalt plateaus and gorges above argan and juniper scrub, with snow on the summits in winter." } },
    { plate:"CHI", lon:102, lat:25, cat:"fossil",
      title:"The Tethys shallows", sub:"Marine reptiles",
      body:"Reptiles went back to the sea within a few million years of the extinction. The Chinese blocks, still separate and ringed by warm shallow water, preserve ichthyosaurs, long-necked sauropterygians and the strange hammer-headed filter feeder Atopodentatus.",
      then:{ where:"Warm Tethyan shelf", icon:"sea",
             text:"Shallow tropical carbonate platforms on isolated blocks east of Pangaea." },
      now:{ where:"Yunnan and Guizhou, China", icon:"broadleaf",
            text:"Karst limestone towers and gorges, subtropical, with evergreen broadleaf forest and rice terraces." } }
  ]
},
{
  id:"jur", name:"Jurassic", ma:155, span:"201–145 million years ago",
  colour:"#34B2C9", accent:"#4FC6DC", view:[-15,10],
  headline:"Pangaea splits into Laurasia and Gondwana",
  body:[
    "A seaway pushes east from the young Central Atlantic and joins the Tethys, cutting the supercontinent in two. North America, Europe and Asia form Laurasia in the north. South America, Africa, India, Australia and Antarctica form Gondwana in the south. This is the only interval when both names describe things that exist at the same time.",
    "Sea level is high and warm shallow seas cover much of Europe. Sauropods reach their maximum size, and the first birds appear.",
    "There is still no grass and no flower. Ground cover is fern; the canopy is conifer, cycad and ginkgo."
  ],
  facts:[
    ["North pole","Open ocean, ice-free"],
    ["South pole","Over Antarctica, forested, no ice sheet"],
    ["Laurasia","North America, Europe, Asia"],
    ["Gondwana","South America, Africa, India, Australia, Antarctica"]
  ],
    plates:{ NAM:[-31.6,41.5,-15.6], EUR:[7.2,32.6,-35], SIB:[-26.8,67.5,-7.8], CHI:[103,20,18],
           IND:[50.2,-46.1,49.2], AFR:[10.2,-19,14.2], SAM:[-26.1,-26.8,-10.7],
           AUS:[91.9,-57.1,-62.5], ANT:[16.2,-64.8,-18.1], MAD:[38.5,-38.7,10.8] },
  ice:[],
  sites:[
    { plate:"NAM", lon:-108.5, lat:40, cat:"fossil",
      title:"Morrison Formation", sub:"The classic dinosaur quarry",
      body:"Allosaurus, Stegosaurus, Apatosaurus, Diplodocus and Brachiosaurus all come from this one rock unit, spread across the American west. The landscape was seasonally dry, with monsoon rains, braided rivers, and ribbons of conifer along the channels rather than continuous forest.",
      then:{ where:"Semi-arid floodplain, about 35° north", icon:"conifer",
             text:"Open country of ferns and horsetails with gallery forest along seasonal rivers. No grass, so 'plains' meant fern prairie." },
      now:{ where:"Colorado, Utah and Wyoming", icon:"scrub",
            text:"High sagebrush steppe and badlands. At Dinosaur National Monument a quarry wall with some 1,500 bones is left in place under a building." } },
    { plate:"AFR", lon:39.5, lat:-9.9, cat:"fossil",
      title:"Tendaguru", sub:"Tanzania",
      body:"German expeditions between 1909 and 1913 moved several hundred tonnes of bone to Berlin on the heads of porters, over a four-day walk to the coast. The mounted Giraffatitan skeleton that came out of it is thirteen metres tall and still the tallest mounted dinosaur in any museum.",
      then:{ where:"Coastal plain on the Gondwanan margin", icon:"cycad",
             text:"Tidal flats and lagoons behind a warm shallow sea, backed by conifer and cycad woodland." },
      now:{ where:"Lindi Region, Tanzania", icon:"broadleaf",
            text:"Miombo woodland of Brachystegia and Julbernardia inland of the Indian Ocean coast, with a long dry season." } },
    { plate:"EUR", lon:11, lat:48.9, cat:"fossil",
      title:"Solnhofen", sub:"Archaeopteryx",
      body:"A tropical archipelago in the Tethys, with oxygen-starved lagoons between the islands where nothing could scavenge a carcass. The limestone is so fine it was used for lithographic printing, and it preserves feathers, jellyfish and insect wings. Archaeopteryx is known from about a dozen specimens, all from here.",
      then:{ where:"Tethyan lagoon, about 30° north", icon:"reef",
             text:"Still, salty, oxygen-poor water between reef islands in a warm shallow sea." },
      now:{ where:"Altmühl valley, Bavaria", icon:"broadleaf",
            text:"Limestone hills and river valleys under beech, spruce and Scots pine, with the quarries still working." } },
    { plate:"ANT", lon:167, lat:-84.3, cat:"fossil",
      title:"Cryolophosaurus", sub:"Mount Kirkpatrick, Antarctica",
      body:"A seven-metre predator with a crest running crossways over its eyes, dug out of frozen rock at 4,000 metres in the Transantarctic Mountains. Antarctica was polar then too, but ice-free and forested, and large dinosaurs lived there year round through the dark winters.",
      then:{ where:"Polar forest, about 75° south", icon:"conifer",
             text:"Conifer and fern forest on a river plain, cool and strongly seasonal, with no permanent ice." },
      now:{ where:"Transantarctic Mountains", icon:"ice",
            text:"Frozen scree at 4,000 metres, worked in a short summer window with rock saws and jackhammers." } },
    { plate:"NAM", lon:-40, lat:36, cat:"sea",
      title:"The Atlantic opens", sub:"A new ocean",
      body:"The Central Atlantic is the oldest part of the modern ocean. Its floor grew from a mid-ocean ridge that is still there, still producing crust at roughly the speed a fingernail grows. Everything east of the North American coast and west of the African coast is younger than this seam.",
      then:{ where:"A narrow new seaway", icon:"sea",
             text:"A long salty gulf between North America and Africa, widening a few centimetres a year." },
      now:{ where:"The Atlantic Ocean", icon:"sea",
            text:"Around 5,000 km across at this latitude, and still widening at about 2.5 centimetres a year." } }
  ]
},
{
  id:"cre", name:"Cretaceous", ma:90, span:"145–66 million years ago",
  colour:"#7FC64E", accent:"#95D468", view:[-30,15],
  headline:"Flowers spread, and the sea cuts North America in half",
  body:[
    "Gondwana comes apart. South America separates from Africa, India breaks away and begins moving north faster than any large plate before or since, and Madagascar is left behind. The South Atlantic opens from the south upward like a zip.",
    "Sea level is the highest of the last 500 million years. A seaway runs from the Arctic to the Gulf of Mexico and splits North America into two islands: Laramidia in the west, Appalachia in the east. Chalk — the compacted skeletons of microscopic algae — accumulates across Europe and the American interior.",
    "Flowering plants appear early in the period and are dominant by the end of it. The forests that dinosaurs walked through in the last ten million years would look far more familiar than those of the Jurassic."
  ],
  facts:[
    ["North pole","Open ocean, ice-free; forested land nearby"],
    ["South pole","Over Antarctica, forested, no ice sheet"],
    ["Sea level","Up to 250 m above today's"],
    ["Ending","Asteroid impact at Chicxulub, 66 million years ago"]
  ],
    plates:{ NAM:[-76.8,53.1,1.8], EUR:[22.1,47.2,-4.5], SIB:[91,62.7,-4.7],
           CHI:[111.5,30.4,11.6], IND:[47.5,-34.4,73.8], AFR:[10,-23.1,12.3],
           SAM:[-38.5,-28.3,-31.4], AUS:[96.1,-51.9,-44.7], ANT:[28.4,-67.6,5.3],
           MAD:[37.5,-32,0] },
  ice:[],
  sites:[
    { plate:"NAM", lon:-100, lat:42, cat:"sea",
      title:"Western Interior Seaway", sub:"North America divided",
      body:"A shallow sea up to 900 metres deep ran the length of the continent. Its floor is now the chalk and shale under Kansas, Nebraska and the Dakotas, full of mosasaurs, the four-metre fish Xiphactinus, and flying reptiles. Dinosaur faunas on the two sides evolved separately.",
      then:{ where:"A continental sea", icon:"sea",
             text:"Warm, shallow and turbid, with no reefs but huge populations of swimming predators." },
      now:{ where:"The Great Plains", icon:"grass",
            text:"Shortgrass prairie and wheat, buffalo grass and blue grama, with the chalk standing up as the Smoky Hill badlands." } },
    { plate:"CHI", lon:120.8, lat:41.6, cat:"fossil",
      title:"Jehol Biota", sub:"Liaoning, China",
      body:"Volcanic ash falling into cold deep lakes preserved feathers, skin, stomach contents and colour-bearing pigment structures. Sinosauropteryx, Microraptor and the flowering plant Archaefructus come from here. It is the single richest source of evidence that birds are dinosaurs.",
      then:{ where:"Temperate volcanic lake district", icon:"conifer",
             text:"Cool forested uplands of conifer, ginkgo and early flowering plants, with frequent ash falls." },
      now:{ where:"Western Liaoning, China", icon:"broadleaf",
            text:"Dry hills and terraced fields, cold winters, with oak, pine and a working fossil quarry economy." } },
    { plate:"IND", lon:76, lat:18, cat:"event",
      title:"India, travelling alone", sub:"A continent in transit",
      body:"India broke from Madagascar around 88 million years ago and crossed the Tethys as an island continent, moving up to 15 centimetres a year. Its plants and animals evolved in isolation for tens of millions of years before it ran into Asia.",
      then:{ where:"An island continent in the Tethys", icon:"palm",
             text:"Tropical and isolated, with its own dinosaurs and, in its rivers, ancestors of the frogs and caecilians still found only in the Western Ghats." },
      now:{ where:"The Deccan, India", icon:"grass",
            text:"Basalt plateau under dry deciduous woodland, teak and acacia, cotton and sorghum on the black soils." } },
    { plate:"ANT", lon:-57, lat:-64, cat:"forest",
      title:"Forests in Antarctica", sub:"James Ross Island",
      body:"Fossil leaves, wood and pollen from the Antarctic Peninsula, then at around 60° south, show a cool temperate rainforest of southern beech, podocarp and araucarian conifer, with ferns and early flowering plants beneath. Hadrosaurs and armoured dinosaurs lived in it.",
      then:{ where:"High-latitude rainforest", icon:"conifer",
             text:"Wet and cool, with very short winter days and a canopy adapted to grow hard through a brief bright summer." },
      now:{ where:"Antarctic Peninsula", icon:"ice",
            text:"Ice cliffs, moss beds and lichen. The two native flowering plants — a hair grass and a pearlwort — are spreading a little as the peninsula warms." } },
    { plate:"EUR", lon:1.3, lat:51, cat:"sea",
      title:"The chalk sea", sub:"Northern Europe",
      body:"Chalk is made almost entirely of coccoliths: calcite plates a few thousandths of a millimetre across, shed by single-celled algae. Hundreds of metres of it accumulated in clear open water over a drowned Europe, a few grains a year.",
      then:{ where:"Clear open shelf sea", icon:"sea",
             text:"Warm water far from any river mouth, clear enough for algae to bloom and settle without mud." },
      now:{ where:"Southern England and northern France", icon:"grass",
            text:"The Downs and the white cliffs. Thin alkaline soil carries chalk grassland — wild thyme, rockrose and about thirty species of orchid." } }
  ]
},
{
  id:"pgn", name:"Paleogene", ma:50, span:"66–23 million years ago",
  colour:"#FD9A52", accent:"#FDA86C", view:[-20,35],
  headline:"A hot planet with forests at both poles",
  body:[
    "The dinosaurs other than birds are gone, mammals have expanded into the space they left, and the planet is passing through the warmest sustained climate of the last 65 million years. There is no permanent ice anywhere.",
    "Laurasia is coming apart. Greenland separates from Europe and the North Atlantic opens; the volcanic rock that erupted along that tear is now Skye, Mull, the Giant's Causeway and eastern Iceland's ancestors.",
    "India reaches Asia. The Tethys begins to close and the Himalaya starts to rise, which over the following tens of millions of years pulls carbon dioxide out of the air through weathering and helps cool the planet back down."
  ],
  facts:[
    ["North pole","Ocean at roughly 23°C in summer, no sea ice"],
    ["South pole","Over Antarctica, still forested, glaciation from 34 Ma"],
    ["Climate","Warmest sustained interval since the dinosaurs"],
    ["Collision","India meets Asia; the Himalaya begins"]
  ],
    plates:{ NAM:[-91.1,47.8,-1.9], EUR:[20.5,51,-3.2], SIB:[96.8,64.4,-1], CHI:[109,26,3.5],
           IND:[71,5.9,-29.1], AFR:[13,-4.2,-8.6], SAM:[-47,-26,6.6], AUS:[121,-48,-7.9],
           ANT:[0.9,-83,0.4], MAD:[41,-28,0] },
  ice:[],
  sites:[
    { plate:"NAM", lon:-90, lat:79.4, cat:"forest",
      title:"Axel Heiberg fossil forest", sub:"Canadian High Arctic",
      body:"Stumps of Metasequoia up to two and a half metres across, still rooted in their soil with leaf litter on top. The wood is not petrified — it is mummified, dry enough to burn. These trees grew at about 79° north, through four months of continuous darkness every year.",
      then:{ where:"Polar swamp forest", icon:"swamp",
             text:"Dawn redwood and swamp cypress on a warm wet coastal plain, dropping their needles for the dark winter." },
      now:{ where:"Axel Heiberg Island, Nunavut", icon:"tundra",
            text:"Polar desert. A few centimetres of Arctic willow, saxifrage and moss, and the stumps still sticking out of the frozen ground." } },
    { plate:"EUR", lon:0, lat:51.5, cat:"forest",
      title:"London Clay", sub:"A tropical coast at 50° north",
      body:"The clay under London has produced thousands of fossil fruits and seeds, and the list reads like Southeast Asia: palms, mangrove palm, cinnamon, magnolia, custard apple. Crocodilians and turtles lived in the estuary. The Thames basin was a tropical sea margin.",
      then:{ where:"Warm shallow sea and mangrove coast", icon:"palm",
             text:"A muddy tropical estuary opening into a warm shelf sea, fringed with Nypa mangrove palm." },
      now:{ where:"London", icon:"city",
            text:"Built on it. The clay is what the Underground tunnels through, and it shrinks and swells enough to crack foundations in a dry summer." } },
    { plate:"EUR", lon:8.75, lat:49.9, cat:"fossil",
      title:"Messel Pit", sub:"47 million years old",
      body:"A flooded volcanic crater with stagnant bottom water, which preserved mammals complete with fur, gut contents and stomach bacteria. Bats are preserved with their last meal identifiable to species, and horses the size of a fox terrier are preserved pregnant.",
      then:{ where:"Crater lake in subtropical forest", icon:"broadleaf",
             text:"A deep maar lake ringed by warm humid forest, occasionally releasing gas that killed animals at the surface." },
      now:{ where:"Hesse, Germany", icon:"broadleaf",
            text:"An abandoned oil-shale quarry near Darmstadt, surrounded by beech and oak woodland and farmland." } },
    { plate:"IND", lon:78, lat:30, cat:"event",
      title:"India hits Asia", sub:"The Himalaya begins",
      body:"The northern edge of India met the southern edge of Asia between about 55 and 50 million years ago, and neither could sink, so both crumpled. Marine limestone from the closed Tethys now sits near the summit of Everest, with fossil sea-floor shells in it at 8,800 metres.",
      then:{ where:"A closing ocean", icon:"sea",
             text:"The last of the Tethys being squeezed out between two converging continents." },
      now:{ where:"The Himalaya", icon:"ice",
            text:"The highest mountains on Earth, still rising about a centimetre a year, with rhododendron and birch forest below the treeline and ice above it." } },
    { plate:"NAM", lon:-110, lat:41.5, cat:"forest",
      title:"Green River lakes", sub:"Wyoming, Utah, Colorado",
      body:"Three large subtropical lakes laid down paper-thin annual layers for millions of years. Fossil palms, crocodiles and stingrays come out of them, alongside more complete fossil fish than anywhere else on Earth.",
      then:{ where:"Subtropical lake basin", icon:"palm",
             text:"Warm lakes fringed with palm and sycamore, ringed by rising mountains." },
      now:{ where:"Green River basin, Wyoming", icon:"scrub",
            text:"Cold high desert above 2,000 m, sagebrush and greasewood, with winters well below freezing." } }
  ]
},
{
  id:"now", name:"Today", ma:0, span:"The present",
  colour:"#F9F97F", accent:"#E8E86A", view:[-30,12],
  headline:"The pieces, and where they ended up",
  body:[
    "Antarctica sits on the pole with an ice sheet up to 4.8 kilometres thick, in place for about 34 million years. The Arctic is an ocean with a floating ice lid. This is unusual: for most of the last 500 million years the Earth had ice at neither pole.",
    "Gondwana is still legible in the living world. Southern beech, araucarian conifers and podocarps are spread across Chile, New Zealand, Tasmania and New Guinea — not because they crossed oceans, but because the land they grew on split apart beneath them.",
    "The Atlantic is still opening at about 2.5 centimetres a year, Africa is still pushing into Europe, and India is still driving into Asia."
  ],
  facts:[
    ["North pole","Ocean, covered by drifting sea ice"],
    ["South pole","Antarctica, under roughly 2,700 m of ice"],
    ["Ice on land","About 10 percent of the land surface"],
    ["Still moving","Atlantic widening; Himalaya and Alps rising"]
  ],
    plates:{ NAM:[-95,50,0], EUR:[15,52,0], SIB:[105,65,0], CHI:[108,28,0], IND:[79,20,0],
           AFR:[18,2,0], SAM:[-60,-20,0], AUS:[134,-25,0], ANT:[0,-83,0], MAD:[47,-19,0] },
  ice:[{ plate:"ANT", lon:0, lat:-90, r:22 }],
  sites:[
    { plate:"SAM", lon:-72.5, lat:-41.5, cat:"forest",
      title:"Valdivian rainforest", sub:"Living Gondwana",
      body:"Southern beech, or Nothofagus, grows in Chile, Argentina, New Zealand, Tasmania, mainland Australia and New Guinea, and nowhere else. Its seeds do not travel far or survive salt water. The distribution is a map of a continent that broke up around it.",
      then:{ where:"Gondwanan forest", icon:"conifer",
             text:"The same lineage grew across southern Gondwana, Antarctica included, when the pieces were joined." },
      now:{ where:"Los Ríos and Los Lagos, Chile", icon:"broadleaf",
            text:"Cool temperate rainforest of coigüe, ulmo and alerce, with three metres of rain a year and a fern and bamboo understorey." } },
    { plate:"AUS", lon:150.5, lat:-33.2, cat:"forest",
      title:"Wollemi pine", sub:"Found alive in 1994",
      body:"Known only as a fossil until a park ranger abseiled into a canyon in the Blue Mountains and found fewer than a hundred trees growing. Its lineage goes back more than 100 million years, and the wild location is kept secret to protect it from introduced root pathogens.",
      then:{ where:"Cretaceous Gondwanan forest", icon:"conifer",
             text:"Part of a widespread araucarian forest across southern Gondwana." },
      now:{ where:"Wollemi National Park, New South Wales", icon:"conifer",
            text:"A single sandstone canyon with its own damp microclimate, surrounded by dry eucalypt forest." } },
    { plate:"ANT", lon:0, lat:-90, cat:"ice",
      title:"The South Pole", sub:"Under the ice",
      body:"The ice at the geographic pole is about 2,700 metres thick and the bedrock beneath is near sea level. Ice cores drilled nearby hold continuous atmospheric records going back 800,000 years, with air bubbles that can be sampled directly.",
      then:{ where:"Forested, repeatedly", icon:"conifer",
             text:"This continent carried Glossopteris forest in the Permian and beech and conifer rainforest in the Cretaceous." },
      now:{ where:"Antarctic plateau", icon:"ice",
            text:"Nothing grows. Mean annual temperature around −49°C, and the nearest plants are mosses on the peninsula, 2,000 km away." } },
    { plate:"AFR", lon:15, lat:0, cat:"forest",
      title:"Congo Basin", sub:"On old Gondwanan crust",
      body:"The rock under the Congo rainforest is some of the oldest continental crust on the planet, and it carried the Karoo glaciation in the Carboniferous. The forest sitting on it now is the second largest in the world and holds about 10,000 plant species, a third of them found nowhere else.",
      then:{ where:"Glaciated, then desert", icon:"ice",
             text:"Under ice in the Carboniferous; deep inside Pangaea's arid interior in the Permian and Triassic." },
      now:{ where:"Central Africa", icon:"broadleaf",
            text:"Lowland tropical rainforest, 1,600–2,000 mm of rain a year, with a canopy 40 m up and okoumé and sapele above it." } },
    { plate:"NAM", lon:-89.5, lat:21.4, cat:"event",
      title:"Chicxulub", sub:"66 million years ago",
      body:"A 10-kilometre asteroid struck a shallow sea over sulphur-rich rock, which is part of why the impact was so lethal: vaporised sulphate blocked sunlight for years. The 180-kilometre crater is buried under the Yucatán, traceable at the surface only as a ring of sinkholes.",
      then:{ where:"Shallow carbonate platform", icon:"reef",
             text:"Warm shelf sea over gypsum and limestone, on the southern edge of North America." },
      now:{ where:"Yucatán, Mexico", icon:"broadleaf",
            text:"Flat limestone plain under dry tropical forest, with the crater rim marked by a semicircle of cenotes." } }
  ]
}
];
