/* ===================== source tiers =====================
   How far each source in js/sources.js can be trusted, scored with the rubric
   in docs/source-rubric.md. Keyed by source number; the bibliographic fields
   stay in SOURCES.

   Each record gives nine scores of 0 to 2 (provenance, author expertise,
   peer or editorial review, primary data, citations, corroboration, stated
   methods, conflicts of interest, recency), the tier they produce, and a
   one-line justification. Scores start from the rubric profile for the kind
   of source and are adjusted where the source earns a different score.

   Not yet loaded by any page. sources.html can read SOURCE_TIERS[n].tier
   to print the tier beside each entry.                                    */

const SOURCE_TIER_KEYS = ["prov","exp","rev","data","cite","corr","meth","coi","rec"];

/* The rubric: total to tier, then the gates in section 4. */
function tierFromScores(s){
  const total = SOURCE_TIER_KEYS.reduce((a, k) => a + s[k], 0);
  const rank = "ABCDE";
  let tier = total >= 15 ? "A" : total >= 10 ? "B" : total >= 7 ? "C" : total >= 4 ? "D" : "E";
  const cap = c => { if (rank.indexOf(tier) < rank.indexOf(c)) tier = c; };
  if (s.rev < 2 || s.data < 1) cap("B");             // 1. A needs review and data
  if (s.rev === 0) cap(s.exp === 2 ? "C" : "D");      // 2. no review
  if (s.coi === 0) cap("D");                          // 3. direct stake
  if (s.corr === 0 || s.rec === 0) cap("D");          // 5. superseded on the point
  if (s.data === 0) cap("C");                         // 6. restatement only
  if (s.prov === 0) tier = "E";                       // 4. untraceable
  return tier;
}

const SOURCE_TIERS = {
  1:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  2:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:1, corr:2, meth:1, coi:2, rec:2,
    note:"Institutional reference dataset." },
  3:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:2, meth:0, coi:2, rec:2,
    note:"Credit or licence record; supports no geological claim." },
  4:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:2, meth:0, coi:2, rec:2,
    note:"Credit or licence record; supports no geological claim." },
  5:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:2, meth:0, coi:2, rec:2,
    note:"Credit or licence record; supports no geological claim." },
  6:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:2, meth:0, coi:1, rec:2,
    note:"The project's own licence file." },
  7:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  8:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"Cleveland Museum blog on research by its own associate." },
  9:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  10:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  11:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  12:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  13:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  14:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  15:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  16:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  17:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  18:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  19:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  20:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  21:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  22:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"The Conversation piece written by the MNHN researchers on their own work (Nel et al. 2018)." },
  23:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  24:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  25:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  26:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  27:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"Field Museum blog story on its own researchers' finding." },
  28:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  29:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"NHM London news story on its own researchers' finding." },
  30:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  31:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  32:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  33:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  34:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  35:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  36:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  37:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  38:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  39:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  40:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  41:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  42:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  43:{ tier:"C", prov:2, exp:0, rev:1, data:0, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Sci.News, a news site that rewrites press releases." },
  44:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  45:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  46:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUCN World Heritage Outlook assessment." },
  47:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  48:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  49:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  50:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  51:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  52:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  53:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  54:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  55:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  56:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  57:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  58:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  59:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  60:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  61:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  62:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  63:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  64:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  65:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  66:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  67:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  68:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  69:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  70:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:2, corr:1, meth:0, coi:2, rec:2,
    note:"NZ Birds Online species account; expert-written, referenced." },
  71:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"New Zealand Department of Conservation page." },
  72:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  73:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  74:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  75:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  76:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  77:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  78:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  79:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  80:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"New Zealand Department of Conservation page." },
  81:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  82:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  83:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  84:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  85:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  86:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  87:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUCN World Heritage Outlook assessment." },
  88:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  89:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  90:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  91:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  92:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  93:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"Survey or agency technical report, map or memoir." },
  94:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  95:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  96:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  97:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  98:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  99:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  100:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  101:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  102:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  103:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  104:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  105:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  106:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  107:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  108:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  109:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Field Museum blog by the collections manager." },
  110:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  111:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  112:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  113:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  114:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  115:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:1,
    note:"University museum newsletter article by a professor." },
  116:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  117:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  118:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  119:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  120:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  121:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  122:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  123:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  124:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  125:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  126:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  127:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"Museum Wales news article on its own specimens." },
  128:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  129:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  130:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  131:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  132:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  133:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  134:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  135:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"ROM collection record for a catalogued specimen." },
  136:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  137:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  138:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  139:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  140:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"UNESCO Global Geopark site page; promotes the site." },
  141:{ tier:"C", prov:2, exp:0, rev:1, data:0, cite:0, corr:1, meth:0, coi:1, rec:2,
    note:"Dudley Council nature-reserve page." },
  142:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  143:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  144:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"Field Museum blog story on its own researchers' finding." },
  145:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  146:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  147:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  148:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  149:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  150:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  151:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  152:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  153:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  154:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"Field Museum blog story on its own researchers' finding." },
  155:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  156:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"NHM Utah article on research by its own staff." },
  157:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  158:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  159:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  160:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  161:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"BYU department page on its own specimen." },
  162:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  163:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  164:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  165:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  166:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  167:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  168:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  169:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  170:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  171:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  172:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  173:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  174:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  175:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  176:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  177:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  178:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  179:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  180:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  181:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  182:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  183:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  184:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"North Dakota Geological Survey fossil map sheet." },
  185:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological survey educational page." },
  186:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:0, corr:1, meth:0, coi:1, rec:2,
    note:"Museum 'About' page." },
  187:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  188:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  189:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  190:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  191:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  192:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  193:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  194:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  195:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  196:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  197:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  198:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  199:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  200:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  201:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  202:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  203:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  204:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  205:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  206:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  207:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  208:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  209:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  210:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUGS Geological Heritage record." },
  211:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:1, corr:1, meth:0, coi:1, rec:2,
    note:"University press release on its own researchers' finding." },
  212:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:2, corr:1, meth:0, coi:1, rec:2,
    note:"Joggins Fossil Institute, the operator of the World Heritage site; lists research publications." },
  213:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:2, corr:1, meth:0, coi:1, rec:2,
    note:"Joggins Fossil Institute, the operator of the World Heritage site; lists research publications." },
  214:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  215:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  216:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUGS Geological Heritage record." },
  217:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  218:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  219:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"Scholarly encyclopaedia chapter by specialists (Elsevier Encyclopedia of Geology)." },
  220:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  221:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  222:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  223:{ tier:"C", prov:2, exp:1, rev:1, data:0, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum news blog written by museum staff." },
  224:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  225:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  226:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"USGS This Dynamic Earth, a reviewed general-interest publication." },
  227:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  228:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  229:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  230:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  231:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  232:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  233:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  234:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  235:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  236:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  237:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  238:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  239:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  240:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  241:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUCN World Heritage Outlook assessment." },
  242:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  243:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  244:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  245:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  246:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  247:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  248:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  249:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological survey educational page." },
  250:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  251:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  252:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  253:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUCN World Heritage Outlook assessment." },
  254:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  255:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  256:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  257:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  258:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  259:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  260:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  261:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  262:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  263:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  264:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  265:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  266:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"Hunter College course text by Stoffer (USGS) and Messina." },
  267:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  268:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  269:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  270:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  271:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  272:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  273:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"IUCN World Heritage Outlook assessment." },
  274:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  275:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  276:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  277:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"Textbook or scholarly reference synthesis." },
  278:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:2, meth:2, coi:2, rec:2,
    note:"GPlates software documentation; describes the method, not a result." },
  279:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  280:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  281:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  282:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  283:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Scotese PALEOMAP plate model files; primary dataset without separate peer review." },
  284:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  285:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  286:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  287:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  288:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  289:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  290:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  291:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  292:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  293:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  294:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  295:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  296:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  297:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  298:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  299:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  300:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  301:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  302:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  303:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  304:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  305:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  306:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  307:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  308:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  309:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  310:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  311:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  312:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  313:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  314:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  315:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  316:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  317:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  318:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:2,
    note:"Refereed review, monograph or special-publication chapter." },
  319:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  320:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  321:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  322:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  323:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological survey educational page." },
  324:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  325:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  326:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  327:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  328:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  329:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  330:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  331:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"USGS This Dynamic Earth, a reviewed general-interest publication." },
  332:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  333:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  334:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  335:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  336:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  337:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  338:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  339:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  340:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  341:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  342:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  343:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  344:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  345:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  346:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  347:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  348:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  349:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  350:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  351:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  352:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  353:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  354:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  355:{ tier:"A", prov:2, exp:2, rev:2, data:1, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"NPS paleontological inventory chapter; reviewed agency report compiling primary work." },
  356:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"Survey or agency technical report, map or memoir." },
  357:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  358:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  359:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  360:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological Society of London education resource." },
  361:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological Society of London education resource." },
  362:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological Society of London education resource." },
  363:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological Society of London education resource." },
  364:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  365:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  366:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  367:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  368:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  369:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  370:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  371:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  372:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  373:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  374:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  375:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  376:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  377:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"Survey or agency technical report, map or memoir." },
  378:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  379:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  380:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  381:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  382:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  383:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  384:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  385:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  386:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  387:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"Survey or agency technical report, map or memoir." },
  388:{ tier:"B", prov:1, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"NPS Geologic Resource Evaluation report; copy at npshistory.com rather than an NPS address." },
  389:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  390:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  391:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  392:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  393:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  394:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  395:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  396:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  397:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  398:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  399:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  400:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  401:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  402:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"Survey or agency technical report, map or memoir." },
  403:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"BGS educational pages written by survey geologists." },
  404:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"BGS memoir (Geology of London), served on Earthwise." },
  405:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"BGS memoir (Geology of London), served on Earthwise." },
  406:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"BGS memoir (Geology of London), served on Earthwise." },
  407:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:1,
    note:"BGS memoir (Geology of London), served on Earthwise." },
  408:{ tier:"B", prov:1, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:1,
    note:"Geological Conservation Review volume (JNCC); text hosted by the Scottish Geology Trust." },
  409:{ tier:"B", prov:1, exp:2, rev:2, data:1, cite:2, corr:2, meth:1, coi:2, rec:1,
    note:"Geological Conservation Review volume (JNCC); text hosted by the Scottish Geology Trust." },
  410:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  411:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  412:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:1, corr:2, meth:1, coi:2, rec:2,
    note:"Institutional reference dataset." },
  413:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:1, corr:2, meth:1, coi:2, rec:1,
    note:"Previous edition of the ICS chart, kept for the dates it gave." },
  414:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:0, corr:2, meth:0, coi:2, rec:2,
    note:"CGMW colour table; supports colours only." },
  415:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  416:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  417:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  418:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  419:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  420:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  421:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  422:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NHM London Discover or Dino Directory page." },
  423:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"Museum, park or university page written by curators or staff scientists." },
  424:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  425:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  426:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  427:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  428:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  429:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  430:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  431:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  432:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  433:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  434:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  435:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  436:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  437:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  438:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  439:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  440:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  441:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  442:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NSIDC explainer by data-centre scientists." },
  443:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"USGS This Dynamic Earth, a reviewed general-interest publication." },
  444:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  445:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  446:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  447:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  448:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  449:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  450:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  451:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  452:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  453:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  454:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  455:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:1,
    note:"UCMP online exhibit; written by museum staff and students, mostly 1990s." },
  456:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:2, corr:2, meth:0, coi:2, rec:1,
    note:"BGS British Regional Geology or Bedrock Geology UK text, served on Earthwise." },
  457:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"BGS Lexicon of Named Rock Units entry." },
  458:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NPS geology article written by park or partner geologists, with references." },
  459:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  460:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  461:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  462:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  463:{ tier:"B", prov:2, exp:2, rev:2, data:1, cite:1, corr:2, meth:0, coi:2, rec:1,
    note:"Geological survey educational page." },
  464:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  465:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  466:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  467:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  468:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  469:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  470:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  471:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Museum or agency page by education or communications staff." },
  472:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  473:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  474:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  475:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  476:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  477:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  478:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  479:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  480:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  481:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"NPS park page." },
  482:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"NSIDC explainer by data-centre scientists." },
  483:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"National Antarctic programme page." },
  484:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  485:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  486:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  487:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:1, corr:1, meth:0, coi:2, rec:2,
    note:"ROM and Parks Canada Burgess Shale site, written by ROM palaeontologists." },
  488:{ tier:"B", prov:2, exp:1, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"Parks Canada visitor page." },
  489:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  490:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  491:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  492:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  493:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  494:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  495:{ tier:"B", prov:2, exp:2, rev:1, data:2, cite:1, corr:2, meth:0, coi:2, rec:2,
    note:"SCAR Composite Gazetteer record; authoritative for the place name and position." },
  496:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  497:{ tier:"B", prov:2, exp:2, rev:1, data:1, cite:0, corr:1, meth:0, coi:2, rec:2,
    note:"National Antarctic programme page." },
  498:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  499:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  500:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  501:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  502:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  503:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  504:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  505:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  506:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  507:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  508:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  509:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  510:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  511:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  512:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  513:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  514:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." },
  515:{ tier:"A", prov:2, exp:2, rev:2, data:2, cite:2, corr:1, meth:2, coi:2, rec:2,
    note:"Research paper in a refereed journal." }
};
