/* ===================== sources =====================
   Every reference the tool cites. Entries are numbered once and keep their
   number; sites, animals, comparisons, layers and periods point at them with
   `sources:[12, 34]`, and sources.html lists them by group.

   An entry:
     n         its number, never reused
     group     one of SOURCE_GROUPS
     authors   people, or the organisation that published it
     year      null for an undated web page
     title, container (journal and pages, publisher, or website)
     url       a DOI link where there is one
     accessed  the date the link was last checked

   Sourcing rules: peer-reviewed papers and monographs first, then geological
   surveys, museums, park services and universities. Science press is used for
   framing only, never as the sole source for a number. No encyclopaedias,
   blogs, content farms or dealers.                                          */

const SOURCE_GROUPS = [
  { id:"method",      title:"Reconstruction method" },
  { id:"periods",     title:"Periods" },
  { id:"sites",       title:"Sites" },
  { id:"animals",     title:"Animals" },
  { id:"comparisons", title:"Comparisons" },
  { id:"layers",      title:"Layers" },
  { id:"terrain",     title:"Terrain" },
  { id:"data",        title:"Data, fonts and silhouettes" }
];

const SOURCES = [
  { n:1, group:"data", authors:"Cohen, K. M.; Finney, S. C.; Gibbard, P. L.; Fan, J.-X.", year:2013,
    title:"The ICS International Chronostratigraphic Chart",
    container:"Episodes 36(3): 199–204. Period boundaries follow the chart as updated",
    url:"https://doi.org/10.18814/epiiugs/2013/v36i3/002", accessed:"2026-09-19" },
  { n:2, group:"data", authors:"International Commission on Stratigraphy", year:2024,
    title:"International Chronostratigraphic Chart, v2024/12",
    container:"stratigraphy.org. Source of the period dates and of the period colours used in the timeline and the rock columns",
    url:"https://stratigraphy.org/chart", accessed:"2026-09-19" },
  { n:3, group:"data", authors:"Production Type", year:null,
    title:"Newsreader",
    container:"Typeface, served by Google Fonts under the SIL Open Font License 1.1",
    url:"https://fonts.google.com/specimen/Newsreader", accessed:"2026-09-19" },
  { n:4, group:"data", authors:"IBM; Bold Monday", year:null,
    title:"IBM Plex Sans",
    container:"Typeface, served by Google Fonts under the SIL Open Font License 1.1",
    url:"https://fonts.google.com/specimen/IBM+Plex+Sans", accessed:"2026-09-19" },
  { n:5, group:"data", authors:"SIL International", year:2007,
    title:"SIL Open Font License, version 1.1",
    container:"openfontlicense.org",
    url:"https://openfontlicense.org/", accessed:"2026-09-19" },
  { n:6, group:"data", authors:"Tetrud, J.", year:2026,
    title:"GeoGlobe licence: MIT for code, CC BY 4.0 for content",
    container:"github.com/juliatetrud/geological-history-tool",
    url:"https://github.com/juliatetrud/geological-history-tool/blob/main/LICENSE", accessed:"2026-09-19" },
  { n:7, group:"animals", authors:"Engelman, R. K.", year:2023,
    title:"A Devonian Fish Tale: A New Method of Body Length Estimation Suggests Much Smaller Sizes for Dunkleosteus terrelli (Placodermi: Arthrodira)",
    container:"Diversity 15(3): 318",
    url:"https://doi.org/10.3390/d15030318", accessed:"2026-09-19" },
  { n:8, group:"animals", authors:"Cleveland Museum of Natural History", year:2025,
    title:"Meet Dunk: Ohio's Ancient Apex Predator",
    container:"CMNH science blog",
    url:"https://www.cmnh.org/learn/science-blog/2025/02/07/meet-dunk-ohios-ancient-apex-predator", accessed:"2026-09-19" },
  { n:9, group:"animals", authors:"Daeschler, E. B.; Shubin, N. H.; Jenkins, F. A.", year:2006,
    title:"A Devonian tetrapod-like fish and the evolution of the tetrapod body plan",
    container:"Nature 440: 757-763",
    url:"https://doi.org/10.1038/nature04639", accessed:"2026-09-19" },
  { n:10, group:"animals", authors:"University of Chicago, Biological Sciences Division", year:2022,
    title:"New fossil shows four-legged fishapod that returned to the water while Tiktaalik ventured onto land",
    container:"UChicago Biological Sciences Division news",
    url:"https://biologicalsciences.uchicago.edu/news/new-fossil-shows-four-legged-fishapod-returned-water", accessed:"2026-09-19" },
  { n:11, group:"animals", authors:"University of Chicago Medicine", year:2008,
    title:"Fishapod reveals origins of head and neck structures of first land animals",
    container:"UChicago Medicine Forefront news",
    url:"https://www.uchicagomedicine.org/forefront/news/2008/october/fishapod-reveals-origins-of-head-and-neck-structures-of-first-land-animals", accessed:"2026-09-19" },
  { n:12, group:"animals", authors:"University of Aberdeen", year:null,
    title:"The Rhynie Chert Fauna: Trigonotarbids",
    container:"The Rhynie Chert Flora and Fauna (University of Aberdeen learning resource)",
    url:"https://www.abdn.ac.uk/rhynie/trig.htm", accessed:"2026-09-19" },
  { n:13, group:"animals", authors:"Dunlop, J. A.; Garwood, R. J.", year:2017,
    title:"Terrestrial invertebrates in the Rhynie chert ecosystem",
    container:"Philosophical Transactions of the Royal Society B 373(1739): 20160493",
    url:"https://doi.org/10.1098/rstb.2016.0493", accessed:"2026-09-19" },
  { n:14, group:"animals", authors:"Garwood, R.; Dunlop, J.", year:2014,
    title:"The walking dead: Blender as a tool for paleontologists with a case study on extinct arachnids",
    container:"Journal of Paleontology 88(4): 735-746",
    url:"https://doi.org/10.1666/13-088", accessed:"2026-09-19" },
  { n:15, group:"animals", authors:"Gess, R.; Ahlberg, P. E.", year:2018,
    title:"A tetrapod fauna from within the Devonian Antarctic Circle",
    container:"Science 360(6393): 1120-1124",
    url:"https://doi.org/10.1126/science.aaq1645", accessed:"2026-09-19" },
  { n:16, group:"animals", authors:"University of the Witwatersrand", year:2018,
    title:"First tetrapods of Africa lived within the Devonian Antarctic Circle",
    container:"Wits University research news",
    url:"https://www.wits.ac.za/news/latest-news/research-news/2018/2018-06/first-tetrapods-of-africa-lived-within-the-devonian-antarctic-circle.html", accessed:"2026-09-19" },
  { n:17, group:"animals", authors:"Bechard, I.; Arsenault, F.; Cloutier, R.; Kerr, J.", year:2014,
    title:"The Devonian placoderm fish Bothriolepis canadensis revisited with three-dimensional digital imagery",
    container:"Palaeontologia Electronica 17(1): 2A",
    url:"https://doi.org/10.26879/417", accessed:"2026-09-19" },
  { n:18, group:"animals", authors:"Cloutier, R.", year:2013,
    title:"Great Canadian Lagerstatten 4. The Devonian Miguasha Biota (Quebec): UNESCO World Heritage Site and a Time Capsule in the Early History of Vertebrates",
    container:"Geoscience Canada 40(2): 149-163",
    url:"https://doi.org/10.12789/geocanj.2013.40.008", accessed:"2026-09-19" },
  { n:19, group:"animals", authors:"Falcon-Lang, H. J.; Benton, M. J.; Braddy, S. J.; Davies, S. J.", year:2006,
    title:"The Pennsylvanian tropical biome reconstructed from the Joggins Formation of Nova Scotia, Canada",
    container:"Journal of the Geological Society 163(3): 561-576",
    url:"https://doi.org/10.1144/0016-764905-063", accessed:"2026-09-19" },
  { n:20, group:"animals", authors:"Nel, A.; Prokop, J.; Pecharova, M.; Engel, M. S.; Garrouste, R.", year:2018,
    title:"Palaeozoic giant dragonflies were hawker predators",
    container:"Scientific Reports 8: 12141",
    url:"https://doi.org/10.1038/s41598-018-30629-w", accessed:"2026-09-19" },
  { n:21, group:"animals", authors:"Clapham, M. E.; Karr, J. A.", year:2012,
    title:"Environmental and biotic controls on the evolutionary history of insect body size",
    container:"Proceedings of the National Academy of Sciences 109(27): 10927-10930",
    url:"https://doi.org/10.1073/pnas.1204026109", accessed:"2026-09-19" },
  { n:22, group:"animals", authors:"Garrouste, R.; Nel, A. (Museum national d'Histoire naturelle)", year:2018,
    title:"En direct des especes : les libellules geantes du Paleozoique sont-elles encore parmi nous ?",
    container:"The Conversation (France)",
    url:"https://theconversation.com/en-direct-des-especes-les-libellules-geantes-du-paleozo-que-sont-elles-encore-parmi-nous-101783", accessed:"2026-09-19", tier:3 },
  { n:23, group:"animals", authors:"Davies, N. S.; Garwood, R. J.; McMahon, W. J.; Schneider, J. W.; Shillito, A. P.", year:2021,
    title:"The largest arthropod in Earth history: insights from newly discovered Arthropleura remains (Serpukhovian Stainmore Formation, Northumberland, England)",
    container:"Journal of the Geological Society 179(3): jgs2021-115",
    url:"https://doi.org/10.1144/jgs2021-115", accessed:"2026-09-19" },
  { n:24, group:"animals", authors:"Lheritier, M.; Edgecombe, G. D.; Garwood, R. J.; et al.", year:2024,
    title:"Head anatomy and phylogenomics show the Carboniferous giant Arthropleura belonged to a millipede-centipede group",
    container:"Science Advances 10(41): eadp6362",
    url:"https://doi.org/10.1126/sciadv.adp6362", accessed:"2026-09-19" },
  { n:25, group:"animals", authors:"McCoy, V. E.; Saupe, E. E.; Lamsdell, J. C.; et al.", year:2016,
    title:"The 'Tully monster' is a vertebrate",
    container:"Nature 532: 496-499",
    url:"https://doi.org/10.1038/nature16992", accessed:"2026-09-19" },
  { n:26, group:"animals", authors:"Mikami, T.; Ikeda, T.; Muramiya, Y.; Hirasawa, T.; Iwasaki, W.", year:2023,
    title:"Three-dimensional anatomy of the Tully monster casts doubt on its presumed vertebrate affinities",
    container:"Palaeontology 66(2): e12646",
    url:"https://doi.org/10.1111/pala.12646", accessed:"2026-09-19" },
  { n:27, group:"animals", authors:"Field Museum", year:2016,
    title:"Monster Mystery Solved",
    container:"Field Museum blog",
    url:"https://www.fieldmuseum.org/blog/monster-mystery-solved", accessed:"2026-09-19" },
  { n:28, group:"animals", authors:"Porro, L. B.; Rayfield, E. J.; Clack, J. A.", year:2022,
    title:"Computed tomography and three-dimensional reconstruction of the skull of the stem tetrapod Crassigyrinus scoticus Watson, 1929",
    container:"Journal of Vertebrate Paleontology 42(4): e2183134",
    url:"https://doi.org/10.1080/02724634.2023.2183134", accessed:"2026-09-19" },
  { n:29, group:"animals", authors:"Natural History Museum, London", year:2023,
    title:"Crushed Scottish fossils reconstructed to reveal ancient predator's skull",
    container:"NHM Discover news",
    url:"https://www.nhm.ac.uk/discover/news/2023/may/crushed-scottish-fossils-reconstructed-reveal-ancient-predators-skull.html", accessed:"2026-09-19" },
  { n:30, group:"animals", authors:"Coates, M. I.; Sequeira, S. E. K.", year:2001,
    title:"A new stethacanthid chondrichthyan from the lower Carboniferous of Bearsden, Scotland",
    container:"Journal of Vertebrate Paleontology 21(3): 438-459",
    url:"https://doi.org/10.1671/0272-4634(2001)021[0438:ANSCFT]2.0.CO;2", accessed:"2026-09-19" },
  { n:31, group:"animals", authors:"University of Glasgow (Hunterian Museum)", year:2001,
    title:"Bearsden Shark is officially named",
    container:"University of Glasgow news archive",
    url:"https://www.gla.ac.uk/news/archiveofnews/2001/november/headline_30055_en.html", accessed:"2026-09-19" },
  { n:32, group:"animals", authors:"University of California Museum of Paleontology", year:null,
    title:"Introduction to the Pelycosaurs",
    container:"UCMP Berkeley online exhibits",
    url:"https://ucmp.berkeley.edu/synapsids/pelycosaurs.html", accessed:"2026-09-19" },
  { n:33, group:"animals", authors:"Bazzana-Adams, K. D.; Evans, D. C.; Reisz, R. R.", year:2023,
    title:"Neurosensory anatomy and function in Dimetrodon, the first terrestrial apex predator",
    container:"iScience 26(4): 106473",
    url:"https://doi.org/10.1016/j.isci.2023.106473", accessed:"2026-09-19" },
  { n:34, group:"animals", authors:"Botha, J.", year:2020,
    title:"The paleobiology and paleoecology of South African Lystrosaurus",
    container:"PeerJ 8: e10408",
    url:"https://doi.org/10.7717/peerj.10408", accessed:"2026-09-19" },
  { n:35, group:"animals", authors:"University of Washington", year:2020,
    title:"Weathering the tough times: Fossil evidence of 'hibernation-like' state in 250-million-year-old Antarctic animal",
    container:"UW News",
    url:"https://www.washington.edu/news/2020/08/27/torpor-lystrosaurus-release/", accessed:"2026-09-19" },
  { n:36, group:"animals", authors:"Benoit, J.; Manger, P. R.; Norton, L.; Fernandez, V.; Rubidge, B. S.", year:2017,
    title:"Synchrotron scanning reveals the palaeoneurology of the head-butting Moschops capensis (Therapsida, Dinocephalia)",
    container:"PeerJ 5: e3496",
    url:"https://doi.org/10.7717/peerj.3496", accessed:"2026-09-19" },
  { n:37, group:"animals", authors:"Day, M. O.; Ramezani, J.; Bowring, S. A.; Sadler, P. M.; Erwin, D. H.; Abdala, F.; Rubidge, B. S.", year:2015,
    title:"When and how did the terrestrial mid-Permian mass extinction occur? Evidence from the tetrapod record of the Karoo Basin, South Africa",
    container:"Proceedings of the Royal Society B 282(1811): 20150834",
    url:"https://doi.org/10.1098/rspb.2015.0834", accessed:"2026-09-19" },
  { n:38, group:"animals", authors:"Tapanila, L.; Pruitt, J.; Pradel, A.; Wilga, C. D.; Ramsay, J. B.; Schlader, R.; Didier, D. A.", year:2013,
    title:"Jaws for a spiral-tooth whorl: CT images reveal novel adaptation and phylogeny in fossil Helicoprion",
    container:"Biology Letters 9(2): 20130057",
    url:"https://doi.org/10.1098/rsbl.2013.0057", accessed:"2026-09-19" },
  { n:39, group:"animals", authors:"Tapanila, L.; Pruitt, J.", year:2013,
    title:"Unraveling species concepts for the Helicoprion tooth whorl",
    container:"Journal of Paleontology 87(6): 965-983",
    url:"https://doi.org/10.1666/12-156", accessed:"2026-09-19" },
  { n:40, group:"animals", authors:"Verriere, A.; Frobisch, J.", year:2022,
    title:"Ontogenetic, dietary, and environmental shifts in Mesosauridae",
    container:"PeerJ 10: e13866",
    url:"https://doi.org/10.7717/peerj.13866", accessed:"2026-09-19" },
  { n:41, group:"animals", authors:"MacDougall, M. J.; Verriere, A.; Wintrich, T.; LeBlanc, A. R. H.; Fernandez, V.; Frobisch, J.", year:2020,
    title:"Conflicting evidence for the use of caudal autotomy in mesosaurs",
    container:"Scientific Reports 10: 7184",
    url:"https://doi.org/10.1038/s41598-020-63625-0", accessed:"2026-09-19" },
  { n:42, group:"animals", authors:"Pineiro, G.; Nunez Demarco, P.; Laurin, M.", year:2025,
    title:"The Largest Mesosaurs Ever Known: Evidence from Scanty Records",
    container:"Fossil Studies 3(1): 1",
    url:"https://doi.org/10.3390/fossils3010001", accessed:"2026-09-19" },
  { n:43, group:"animals", authors:"Sci.News", year:2025,
    title:"Paleontologists Unearth What May Be Largest Known Mesosaurs",
    container:"Sci.News",
    url:"https://www.sci.news/paleontology/largest-known-mesosaurs-13553.html", accessed:"2026-09-19", tier:3 }
];

/* PhyloPic silhouettes used in the Animals panel, one line per image.
   Only CC0 and CC BY images are used. */
const SILHOUETTES = [
  { genus:"Bothriolepis", file:"img/animals/bothriolepis.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Coombs", imagePage:"https://www.phylopic.org/images/5ac3e6ad-bb40-4917-8cfd-810e4e3ba434", note:null },
  { genus:"Dunkleosteus", file:"img/animals/dunkleosteus.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Russell Engelman", imagePage:"https://www.phylopic.org/images/3c9a7513-5b3f-463c-851c-148da2ab4bab", note:null },
  { genus:"Palaeocharinus", file:"img/animals/palaeocharinus.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/19d19934-8486-4e31-9f6c-41db3641f377", note:null },
  { genus:"Tiktaalik", file:"img/animals/tiktaalik.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/10a9bdee-2c86-4f13-a8ae-5ff92dbed2a9", note:null }
];

function sourceByNumber(n){ return SOURCES.find(s => s.n === n); }
function sourceCitation(s){
  return s.authors + (s.year ? " (" + s.year + "). " : ". ") + s.title + ". " + s.container + ".";
}
