/* ===================== sources =====================
   Every reference the tool cites. Entries are numbered once and keep their
   number; sites, animals, comparisons, layers and periods point at them with
   `sources:[12, 34]`, and sources.html lists them by group.

   An entry:
     n         its number, never reused
     group     one of SOURCE_GROUPS
     authors   people, or the organisation that published it
     year      null for an undated web page
     title, container (journal and pages, publisher, or website)
     url       a DOI link where there is one
     accessed  the date the link was last checked

   Sourcing rules: peer-reviewed papers and monographs first, then geological
   surveys, museums, park services and universities. Science press is used for
   framing only, never as the sole source for a number. No encyclopaedias,
   blogs, content farms or dealers.                                          */

const SOURCE_GROUPS = [
  { id:"method",      title:"Reconstruction method" },
  { id:"periods",     title:"Periods" },
  { id:"sites",       title:"Sites" },
  { id:"animals",     title:"Animals" },
  { id:"comparisons", title:"Comparisons" },
  { id:"layers",      title:"Layers" },
  { id:"terrain",     title:"Terrain" },
  { id:"data",        title:"Data, fonts and silhouettes" }
];

const SOURCES = [
  { n:1, group:"data", authors:"Cohen, K. M.; Finney, S. C.; Gibbard, P. L.; Fan, J.-X.", year:2013,
    title:"The ICS International Chronostratigraphic Chart",
    container:"Episodes 36(3): 199–204. Period boundaries follow the chart as updated",
    url:"https://doi.org/10.18814/epiiugs/2013/v36i3/002", accessed:"2026-09-19" },
  { n:2, group:"data", authors:"International Commission on Stratigraphy", year:2024,
    title:"International Chronostratigraphic Chart, v2024/12",
    container:"stratigraphy.org. Source of the period dates and of the period colours used in the timeline and the rock columns",
    url:"https://stratigraphy.org/chart", accessed:"2026-09-19" },
  { n:3, group:"data", authors:"Production Type", year:null,
    title:"Newsreader",
    container:"Typeface, served by Google Fonts under the SIL Open Font License 1.1",
    url:"https://fonts.google.com/specimen/Newsreader", accessed:"2026-09-19" },
  { n:4, group:"data", authors:"IBM; Bold Monday", year:null,
    title:"IBM Plex Sans",
    container:"Typeface, served by Google Fonts under the SIL Open Font License 1.1",
    url:"https://fonts.google.com/specimen/IBM+Plex+Sans", accessed:"2026-09-19" },
  { n:5, group:"data", authors:"SIL International", year:2007,
    title:"SIL Open Font License, version 1.1",
    container:"openfontlicense.org",
    url:"https://openfontlicense.org/", accessed:"2026-09-19" },
  { n:6, group:"data", authors:"Tetrud, J.", year:2026,
    title:"GeoGlobe licence: MIT for code, CC BY 4.0 for content",
    container:"github.com/juliatetrud/geological-history-tool",
    url:"https://github.com/juliatetrud/geological-history-tool/blob/main/LICENSE", accessed:"2026-09-19" },
  { n:7, group:"animals", authors:"Engelman, R. K.", year:2023,
    title:"A Devonian Fish Tale: A New Method of Body Length Estimation Suggests Much Smaller Sizes for Dunkleosteus terrelli (Placodermi: Arthrodira)",
    container:"Diversity 15(3): 318",
    url:"https://doi.org/10.3390/d15030318", accessed:"2026-09-19" },
  { n:8, group:"animals", authors:"Cleveland Museum of Natural History", year:2025,
    title:"Meet Dunk: Ohio's Ancient Apex Predator",
    container:"CMNH science blog",
    url:"https://www.cmnh.org/learn/science-blog/2025/02/07/meet-dunk-ohios-ancient-apex-predator", accessed:"2026-09-19" },
  { n:9, group:"animals", authors:"Daeschler, E. B.; Shubin, N. H.; Jenkins, F. A.", year:2006,
    title:"A Devonian tetrapod-like fish and the evolution of the tetrapod body plan",
    container:"Nature 440: 757-763",
    url:"https://doi.org/10.1038/nature04639", accessed:"2026-09-19" },
  { n:10, group:"animals", authors:"University of Chicago, Biological Sciences Division", year:2022,
    title:"New fossil shows four-legged fishapod that returned to the water while Tiktaalik ventured onto land",
    container:"UChicago Biological Sciences Division news",
    url:"https://biologicalsciences.uchicago.edu/news/new-fossil-shows-four-legged-fishapod-returned-water", accessed:"2026-09-19" },
  { n:11, group:"animals", authors:"University of Chicago Medicine", year:2008,
    title:"Fishapod reveals origins of head and neck structures of first land animals",
    container:"UChicago Medicine Forefront news",
    url:"https://www.uchicagomedicine.org/forefront/news/2008/october/fishapod-reveals-origins-of-head-and-neck-structures-of-first-land-animals", accessed:"2026-09-19" },
  { n:12, group:"animals", authors:"University of Aberdeen", year:null,
    title:"The Rhynie Chert Fauna: Trigonotarbids",
    container:"The Rhynie Chert Flora and Fauna (University of Aberdeen learning resource)",
    url:"https://www.abdn.ac.uk/rhynie/trig.htm", accessed:"2026-09-19" },
  { n:13, group:"animals", authors:"Dunlop, J. A.; Garwood, R. J.", year:2017,
    title:"Terrestrial invertebrates in the Rhynie chert ecosystem",
    container:"Philosophical Transactions of the Royal Society B 373(1739): 20160493",
    url:"https://doi.org/10.1098/rstb.2016.0493", accessed:"2026-09-19" },
  { n:14, group:"animals", authors:"Garwood, R.; Dunlop, J.", year:2014,
    title:"The walking dead: Blender as a tool for paleontologists with a case study on extinct arachnids",
    container:"Journal of Paleontology 88(4): 735-746",
    url:"https://doi.org/10.1666/13-088", accessed:"2026-09-19" },
  { n:15, group:"animals", authors:"Gess, R.; Ahlberg, P. E.", year:2018,
    title:"A tetrapod fauna from within the Devonian Antarctic Circle",
    container:"Science 360(6393): 1120-1124",
    url:"https://doi.org/10.1126/science.aaq1645", accessed:"2026-09-19" },
  { n:16, group:"animals", authors:"University of the Witwatersrand", year:2018,
    title:"First tetrapods of Africa lived within the Devonian Antarctic Circle",
    container:"Wits University research news",
    url:"https://www.wits.ac.za/news/latest-news/research-news/2018/2018-06/first-tetrapods-of-africa-lived-within-the-devonian-antarctic-circle.html", accessed:"2026-09-19" },
  { n:17, group:"animals", authors:"Bechard, I.; Arsenault, F.; Cloutier, R.; Kerr, J.", year:2014,
    title:"The Devonian placoderm fish Bothriolepis canadensis revisited with three-dimensional digital imagery",
    container:"Palaeontologia Electronica 17(1): 2A",
    url:"https://doi.org/10.26879/417", accessed:"2026-09-19" },
  { n:18, group:"animals", authors:"Cloutier, R.", year:2013,
    title:"Great Canadian Lagerstatten 4. The Devonian Miguasha Biota (Quebec): UNESCO World Heritage Site and a Time Capsule in the Early History of Vertebrates",
    container:"Geoscience Canada 40(2): 149-163",
    url:"https://doi.org/10.12789/geocanj.2013.40.008", accessed:"2026-09-19" },
  { n:19, group:"animals", authors:"Falcon-Lang, H. J.; Benton, M. J.; Braddy, S. J.; Davies, S. J.", year:2006,
    title:"The Pennsylvanian tropical biome reconstructed from the Joggins Formation of Nova Scotia, Canada",
    container:"Journal of the Geological Society 163(3): 561-576",
    url:"https://doi.org/10.1144/0016-764905-063", accessed:"2026-09-19" },
  { n:20, group:"animals", authors:"Nel, A.; Prokop, J.; Pecharova, M.; Engel, M. S.; Garrouste, R.", year:2018,
    title:"Palaeozoic giant dragonflies were hawker predators",
    container:"Scientific Reports 8: 12141",
    url:"https://doi.org/10.1038/s41598-018-30629-w", accessed:"2026-09-19" },
  { n:21, group:"animals", authors:"Clapham, M. E.; Karr, J. A.", year:2012,
    title:"Environmental and biotic controls on the evolutionary history of insect body size",
    container:"Proceedings of the National Academy of Sciences 109(27): 10927-10930",
    url:"https://doi.org/10.1073/pnas.1204026109", accessed:"2026-09-19" },
  { n:22, group:"animals", authors:"Garrouste, R.; Nel, A. (Museum national d'Histoire naturelle)", year:2018,
    title:"En direct des especes : les libellules geantes du Paleozoique sont-elles encore parmi nous ?",
    container:"The Conversation (France)",
    url:"https://theconversation.com/en-direct-des-especes-les-libellules-geantes-du-paleozo-que-sont-elles-encore-parmi-nous-101783", accessed:"2026-09-19", tier:3 },
  { n:23, group:"animals", authors:"Davies, N. S.; Garwood, R. J.; McMahon, W. J.; Schneider, J. W.; Shillito, A. P.", year:2021,
    title:"The largest arthropod in Earth history: insights from newly discovered Arthropleura remains (Serpukhovian Stainmore Formation, Northumberland, England)",
    container:"Journal of the Geological Society 179(3): jgs2021-115",
    url:"https://doi.org/10.1144/jgs2021-115", accessed:"2026-09-19" },
  { n:24, group:"animals", authors:"Lheritier, M.; Edgecombe, G. D.; Garwood, R. J.; et al.", year:2024,
    title:"Head anatomy and phylogenomics show the Carboniferous giant Arthropleura belonged to a millipede-centipede group",
    container:"Science Advances 10(41): eadp6362",
    url:"https://doi.org/10.1126/sciadv.adp6362", accessed:"2026-09-19" },
  { n:25, group:"animals", authors:"McCoy, V. E.; Saupe, E. E.; Lamsdell, J. C.; et al.", year:2016,
    title:"The 'Tully monster' is a vertebrate",
    container:"Nature 532: 496-499",
    url:"https://doi.org/10.1038/nature16992", accessed:"2026-09-19" },
  { n:26, group:"animals", authors:"Mikami, T.; Ikeda, T.; Muramiya, Y.; Hirasawa, T.; Iwasaki, W.", year:2023,
    title:"Three-dimensional anatomy of the Tully monster casts doubt on its presumed vertebrate affinities",
    container:"Palaeontology 66(2): e12646",
    url:"https://doi.org/10.1111/pala.12646", accessed:"2026-09-19" },
  { n:27, group:"animals", authors:"Field Museum", year:2016,
    title:"Monster Mystery Solved",
    container:"Field Museum blog",
    url:"https://www.fieldmuseum.org/blog/monster-mystery-solved", accessed:"2026-09-19" },
  { n:28, group:"animals", authors:"Porro, L. B.; Rayfield, E. J.; Clack, J. A.", year:2022,
    title:"Computed tomography and three-dimensional reconstruction of the skull of the stem tetrapod Crassigyrinus scoticus Watson, 1929",
    container:"Journal of Vertebrate Paleontology 42(4): e2183134",
    url:"https://doi.org/10.1080/02724634.2023.2183134", accessed:"2026-09-19" },
  { n:29, group:"animals", authors:"Natural History Museum, London", year:2023,
    title:"Crushed Scottish fossils reconstructed to reveal ancient predator's skull",
    container:"NHM Discover news",
    url:"https://www.nhm.ac.uk/discover/news/2023/may/crushed-scottish-fossils-reconstructed-reveal-ancient-predators-skull.html", accessed:"2026-09-19" },
  { n:30, group:"animals", authors:"Coates, M. I.; Sequeira, S. E. K.", year:2001,
    title:"A new stethacanthid chondrichthyan from the lower Carboniferous of Bearsden, Scotland",
    container:"Journal of Vertebrate Paleontology 21(3): 438-459",
    url:"https://doi.org/10.1671/0272-4634(2001)021[0438:ANSCFT]2.0.CO;2", accessed:"2026-09-19" },
  { n:31, group:"animals", authors:"University of Glasgow (Hunterian Museum)", year:2001,
    title:"Bearsden Shark is officially named",
    container:"University of Glasgow news archive",
    url:"https://www.gla.ac.uk/news/archiveofnews/2001/november/headline_30055_en.html", accessed:"2026-09-19" },
  { n:32, group:"animals", authors:"University of California Museum of Paleontology", year:null,
    title:"Introduction to the Pelycosaurs",
    container:"UCMP Berkeley online exhibits",
    url:"https://ucmp.berkeley.edu/synapsids/pelycosaurs.html", accessed:"2026-09-19" },
  { n:33, group:"animals", authors:"Bazzana-Adams, K. D.; Evans, D. C.; Reisz, R. R.", year:2023,
    title:"Neurosensory anatomy and function in Dimetrodon, the first terrestrial apex predator",
    container:"iScience 26(4): 106473",
    url:"https://doi.org/10.1016/j.isci.2023.106473", accessed:"2026-09-19" },
  { n:34, group:"animals", authors:"Botha, J.", year:2020,
    title:"The paleobiology and paleoecology of South African Lystrosaurus",
    container:"PeerJ 8: e10408",
    url:"https://doi.org/10.7717/peerj.10408", accessed:"2026-09-19" },
  { n:35, group:"animals", authors:"University of Washington", year:2020,
    title:"Weathering the tough times: Fossil evidence of 'hibernation-like' state in 250-million-year-old Antarctic animal",
    container:"UW News",
    url:"https://www.washington.edu/news/2020/08/27/torpor-lystrosaurus-release/", accessed:"2026-09-19" },
  { n:36, group:"animals", authors:"Benoit, J.; Manger, P. R.; Norton, L.; Fernandez, V.; Rubidge, B. S.", year:2017,
    title:"Synchrotron scanning reveals the palaeoneurology of the head-butting Moschops capensis (Therapsida, Dinocephalia)",
    container:"PeerJ 5: e3496",
    url:"https://doi.org/10.7717/peerj.3496", accessed:"2026-09-19" },
  { n:37, group:"animals", authors:"Day, M. O.; Ramezani, J.; Bowring, S. A.; Sadler, P. M.; Erwin, D. H.; Abdala, F.; Rubidge, B. S.", year:2015,
    title:"When and how did the terrestrial mid-Permian mass extinction occur? Evidence from the tetrapod record of the Karoo Basin, South Africa",
    container:"Proceedings of the Royal Society B 282(1811): 20150834",
    url:"https://doi.org/10.1098/rspb.2015.0834", accessed:"2026-09-19" },
  { n:38, group:"animals", authors:"Tapanila, L.; Pruitt, J.; Pradel, A.; Wilga, C. D.; Ramsay, J. B.; Schlader, R.; Didier, D. A.", year:2013,
    title:"Jaws for a spiral-tooth whorl: CT images reveal novel adaptation and phylogeny in fossil Helicoprion",
    container:"Biology Letters 9(2): 20130057",
    url:"https://doi.org/10.1098/rsbl.2013.0057", accessed:"2026-09-19" },
  { n:39, group:"animals", authors:"Tapanila, L.; Pruitt, J.", year:2013,
    title:"Unraveling species concepts for the Helicoprion tooth whorl",
    container:"Journal of Paleontology 87(6): 965-983",
    url:"https://doi.org/10.1666/12-156", accessed:"2026-09-19" },
  { n:40, group:"animals", authors:"Verriere, A.; Frobisch, J.", year:2022,
    title:"Ontogenetic, dietary, and environmental shifts in Mesosauridae",
    container:"PeerJ 10: e13866",
    url:"https://doi.org/10.7717/peerj.13866", accessed:"2026-09-19" },
  { n:41, group:"animals", authors:"MacDougall, M. J.; Verriere, A.; Wintrich, T.; LeBlanc, A. R. H.; Fernandez, V.; Frobisch, J.", year:2020,
    title:"Conflicting evidence for the use of caudal autotomy in mesosaurs",
    container:"Scientific Reports 10: 7184",
    url:"https://doi.org/10.1038/s41598-020-63625-0", accessed:"2026-09-19" },
  { n:42, group:"animals", authors:"Pineiro, G.; Nunez Demarco, P.; Laurin, M.", year:2025,
    title:"The Largest Mesosaurs Ever Known: Evidence from Scanty Records",
    container:"Fossil Studies 3(1): 1",
    url:"https://doi.org/10.3390/fossils3010001", accessed:"2026-09-19" },
  { n:43, group:"animals", authors:"Sci.News", year:2025,
    title:"Paleontologists Unearth What May Be Largest Known Mesosaurs",
    container:"Sci.News",
    url:"https://www.sci.news/paleontology/largest-known-mesosaurs-13553.html", accessed:"2026-09-19", tier:3 },
  { n:44, group:"animals", authors:"Voss, M.; Antar, M. S. M.; Zalmout, I. S.; Gingerich, P. D.", year:2019,
    title:"Stomach contents of the archaeocete Basilosaurus isis: Apex predator in oceans of the late Eocene",
    container:"PLoS ONE 14(1): e0209021",
    url:"https://doi.org/10.1371/journal.pone.0209021", accessed:"2026-09-19" },
  { n:45, group:"animals", authors:"University of California Museum of Paleontology (Understanding Evolution)", year:null,
    title:"The evolution of whales",
    container:"Understanding Evolution, UC Museum of Paleontology, Berkeley",
    url:"https://evolution.berkeley.edu/what-are-evograms/the-evolution-of-whales/", accessed:"2026-09-19" },
  { n:46, group:"animals", authors:"IUCN World Heritage Outlook", year:null,
    title:"Wadi Al-Hitan (Whale Valley)",
    container:"IUCN World Heritage Outlook site assessment",
    url:"https://worldheritageoutlook.iucn.org/node/1140", accessed:"2026-09-19" },
  { n:47, group:"animals", authors:"Thewissen, J. G. M.; Williams, E. M.; Roe, L. J.; Hussain, S. T.", year:2001,
    title:"Skeletons of terrestrial cetaceans and the relationship of whales to artiodactyls",
    container:"Nature 413: 277-281",
    url:"https://doi.org/10.1038/35095005", accessed:"2026-09-19" },
  { n:48, group:"animals", authors:"Gingerich, P. D.; Wells, N. A.; Russell, D. E.; Shah, S. M. I.", year:1983,
    title:"Origin of whales in epicontinental remnant seas: new evidence from the early Eocene of Pakistan",
    container:"Science 220: 403-406",
    url:"https://doi.org/10.1126/science.220.4595.403", accessed:"2026-09-19" },
  { n:49, group:"animals", authors:"Cooper, L. N.; Thewissen, J. G. M.; Hussain, S. T.", year:2009,
    title:"New middle Eocene archaeocetes (Cetacea: Mammalia) from the Kuldana Formation of northern Pakistan",
    container:"Journal of Vertebrate Paleontology 29(4): 1289-1299",
    url:"https://doi.org/10.1671/039.029.0423", accessed:"2026-09-19" },
  { n:50, group:"animals", authors:"Acosta Hospitaleche, C.", year:2014,
    title:"New giant penguin bones from Antarctica: Systematic and paleobiological significance",
    container:"Comptes Rendus Palevol 13(7): 555-560",
    url:"https://doi.org/10.1016/j.crpv.2014.03.008", accessed:"2026-09-19" },
  { n:51, group:"animals", authors:"Jadwiszczak, P.; Krüger, A.; Mörs, T.", year:2025,
    title:"Fossil and modern penguin tarsometatarsi: cavities, vascularity, and resilience",
    container:"Integrative Zoology 20(3): 551-567",
    url:"https://doi.org/10.1111/1749-4877.12852", accessed:"2026-09-19" },
  { n:52, group:"animals", authors:"National Park Service", year:null,
    title:"Fossil Fish",
    container:"Fossil Butte National Monument, U.S. National Park Service",
    url:"https://www.nps.gov/fobu/learn/nature/fossil-fish.htm", accessed:"2026-09-19" },
  { n:53, group:"animals", authors:"University of California Museum of Paleontology", year:null,
    title:"Localities of the Eocene: The Green River Formation",
    container:"UCMP Berkeley online exhibits",
    url:"https://ucmp.berkeley.edu/tertiary/eoc/greenriver.html", accessed:"2026-09-19" },
  { n:54, group:"animals", authors:"Head, J. J.; Bloch, J. I.; Hastings, A. K.; Bourque, J. R.; Cadena, E. A.; Herrera, F. A.; Polly, P. D.; Jaramillo, C. A.", year:2009,
    title:"Giant boid snake from the Palaeocene neotropics reveals hotter past equatorial temperatures",
    container:"Nature 457: 715-717",
    url:"https://doi.org/10.1038/nature07671", accessed:"2026-09-19" },
  { n:55, group:"animals", authors:"Florida Museum of Natural History", year:null,
    title:"Titanoboa",
    container:"Rare, Beautiful and Fascinating: 100 Years at the Florida Museum (University of Florida)",
    url:"https://www.floridamuseum.ufl.edu/100-years/object/titanoboa/", accessed:"2026-09-19" },
  { n:56, group:"animals", authors:"Franzen, J. L.; Aurich, C.; Habersetzer, J.", year:2015,
    title:"Description of a well preserved fetus of the European Eocene equoid Eurohippus messelensis",
    container:"PLoS ONE 10(10): e0137985",
    url:"https://doi.org/10.1371/journal.pone.0137985", accessed:"2026-09-19" },
  { n:57, group:"animals", authors:"de Mazancourt, V.; Wappler, T.; Wedmann, S.", year:2022,
    title:"Exceptional preservation of internal organs in a new fossil species of freshwater shrimp (Caridea: Palaemonoidea) from the Eocene of Messel (Germany)",
    container:"Scientific Reports 12: 18114",
    url:"https://doi.org/10.1038/s41598-022-23125-9", accessed:"2026-09-19" },
  { n:58, group:"animals", authors:"Simmons, N. B.; Seymour, K. L.; Habersetzer, J.; Gunnell, G. F.", year:2008,
    title:"Primitive Early Eocene bat from Wyoming and the evolution of flight and echolocation",
    container:"Nature 451: 818-821",
    url:"https://doi.org/10.1038/nature06549", accessed:"2026-09-19" },
  { n:59, group:"animals", authors:"Amador, L. I.; Simmons, N. B.; Giannini, N. P.", year:2019,
    title:"Aerodynamic reconstruction of the primitive fossil bat Onychonycteris finneyi (Mammalia: Chiroptera)",
    container:"Biology Letters 15(3): 20180857",
    url:"https://doi.org/10.1098/rsbl.2018.0857", accessed:"2026-09-19" },
  { n:60, group:"animals", authors:"National Park Service", year:null,
    title:"Fossil Mammals",
    container:"Fossil Butte National Monument, U.S. National Park Service",
    url:"https://www.nps.gov/fobu/learn/nature/fossil-mammals.htm", accessed:"2026-09-19" },
  { n:61, group:"animals", authors:"Mustoe, G. E.; Tucker, D. S.; Kemplin, K. L.", year:2012,
    title:"Giant Eocene bird footprints from northwest Washington, USA",
    container:"Palaeontology 55(6): 1293-1305",
    url:"https://doi.org/10.1111/j.1475-4983.2012.01195.x", accessed:"2026-09-19" },
  { n:62, group:"animals", authors:"Angst, D.; Lécuyer, C.; Amiot, R.; Buffetaut, E.; Fourel, F.; Martineau, F.; Legendre, S.; Abourachid, A.; Herrel, A.", year:2014,
    title:"Isotopic and anatomical evidence of an herbivorous diet in the Early Tertiary giant bird Gastornis. Implications for the structure of Paleocene terrestrial ecosystems",
    container:"Naturwissenschaften 101: 313-322",
    url:"https://doi.org/10.1007/s00114-014-1158-2", accessed:"2026-09-19" },
  { n:63, group:"animals", authors:"Western Washington University (University Communications, quoting G. Mustoe, WWU Geology)", year:2010,
    title:"Fossil discovered by WWU geologists proves local existence of giant flightless bird 50M years ago",
    container:"WWU News, Western Washington University",
    url:"https://news.wwu.edu/fossil-discovered-by-wwu-geologists-proves-local-existence-of-giant-flightless-bird-50m-years-ago", accessed:"2026-09-19" },
  { n:64, group:"animals", authors:"Stidham, T. A.; Eberle, J. J.", year:2016,
    title:"The palaeobiology of high latitude birds from the early Eocene greenhouse of Ellesmere Island, Arctic Canada",
    container:"Scientific Reports 6: 20912",
    url:"https://doi.org/10.1038/srep20912", accessed:"2026-09-19" },
  { n:65, group:"animals", authors:"Deng, T.; Lu, X.; Wang, S.; Flynn, L. J.; Sun, D.; He, W.; Chen, S.", year:2021,
    title:"An Oligocene giant rhino provides insights into Paraceratherium evolution",
    container:"Communications Biology 4: 639",
    url:"https://doi.org/10.1038/s42003-021-02170-6", accessed:"2026-09-19" },
  { n:66, group:"animals", authors:"Larramendi, A.", year:2016,
    title:"Shoulder height, body mass, and shape of proboscideans",
    container:"Acta Palaeontologica Polonica 61(3): 537-574",
    url:"https://doi.org/10.4202/app.00136.2014", accessed:"2026-09-19" },
  { n:67, group:"animals", authors:"Ksepka, D. T.", year:2014,
    title:"Flight performance of the largest volant bird",
    container:"Proceedings of the National Academy of Sciences 111(29): 10624-10629",
    url:"https://doi.org/10.1073/pnas.1320297111", accessed:"2026-09-19" },
  { n:68, group:"animals", authors:"Kloess, P. A.; Poust, A. W.; Stidham, T. A.", year:2020,
    title:"Earliest fossils of giant-sized bony-toothed birds (Aves: Pelagornithidae) from the Eocene of Seymour Island, Antarctica",
    container:"Scientific Reports 10: 18286",
    url:"https://doi.org/10.1038/s41598-020-75248-6", accessed:"2026-09-19" },
  { n:69, group:"animals", authors:"Mitchell, K. J.; Llamas, B.; Soubrier, J.; Rawlence, N. J.; Worthy, T. H.; Wood, J.; Lee, M. S. Y.; Cooper, A.", year:2014,
    title:"Ancient DNA reveals elephant birds and kiwi are sister taxa and clarifies ratite bird evolution",
    container:"Science 344: 898-900",
    url:"https://doi.org/10.1126/science.1251981", accessed:"2026-09-19" },
  { n:70, group:"animals", authors:"New Zealand Birds Online (Te Papa, Birds New Zealand, Department of Conservation)", year:null,
    title:"Southern brown kiwi | Tokoeka",
    container:"New Zealand Birds Online",
    url:"https://www.nzbirdsonline.org.nz/species/southern-brown-kiwi", accessed:"2026-09-19" },
  { n:71, group:"animals", authors:"Department of Conservation Te Papa Atawhai (New Zealand)", year:null,
    title:"Facts and threats to kiwi",
    container:"Department of Conservation, New Zealand Government",
    url:"https://www.doc.govt.nz/nature/native-animals/birds/birds-a-z/kiwi/facts/", accessed:"2026-09-19" },
  { n:72, group:"animals", authors:"Nilsson, M. A.; Churakov, G.; Sommer, M.; Tran, N. V.; Zemann, A.; Brosius, J.; Schmitz, J.", year:2010,
    title:"Tracking marsupial evolution using archaic genomic retroposon insertions",
    container:"PLoS Biology 8(7): e1000436",
    url:"https://doi.org/10.1371/journal.pbio.1000436", accessed:"2026-09-19" },
  { n:73, group:"animals", authors:"Fontúrbel, F. E.; Franco, L. M.; Bozinovic, F.; Quintero-Galvis, J. F.; Mejías, C.; Amico, G. C.; Vazquez, M. S.; Sabat, P.; Sánchez-Hernández, J. C.; Watson, D. M.; Saenz-Agudelo, P.; Nespolo, R. F.", year:2022,
    title:"The ecology and evolution of the monito del monte, a relict species from the southern South America temperate forests",
    container:"Ecology and Evolution 12(3): e8645",
    url:"https://doi.org/10.1002/ece3.8645", accessed:"2026-09-19" },
  { n:74, group:"animals", authors:"Poux, C.; Madsen, O.; Marquard, E.; Vieites, D. R.; de Jong, W. W.; Vences, M.", year:2005,
    title:"Asynchronous colonization of Madagascar by the four endemic clades of primates, tenrecs, carnivores, and rodents as inferred from nuclear genes",
    container:"Systematic Biology 54(5): 719-730",
    url:"https://doi.org/10.1080/10635150500234534", accessed:"2026-09-19" },
  { n:75, group:"animals", authors:"Ali, J. R.; Huber, M.", year:2010,
    title:"Mammalian biodiversity on Madagascar controlled by ocean currents",
    container:"Nature 463: 653-656",
    url:"https://doi.org/10.1038/nature08706", accessed:"2026-09-19" },
  { n:76, group:"animals", authors:"Duke Lemur Center, Duke University", year:null,
    title:"Ring-tailed Lemur",
    container:"Duke Lemur Center",
    url:"https://lemur.duke.edu/discover/meet-the-lemurs/ring-tailed-lemur/", accessed:"2026-09-19" },
  { n:77, group:"animals", authors:"Fraser, M. D.; Henderson, B. A. S.; Carstens, P. B.; Fraser, A. D.; Henderson, B. S.; Dukes, M. D.; Bruton, M. N.", year:2020,
    title:"Live coelacanth discovered off the KwaZulu-Natal South Coast, South Africa",
    container:"South African Journal of Science 116(3/4)",
    url:"https://doi.org/10.17159/sajs.2020/7806", accessed:"2026-09-19" },
  { n:78, group:"animals", authors:"Sakaue, J.; Maeda, K.; Miller, M. J.; Sakai, R.; Tahara, K.; Abe, H.; Maeda, K.; Ida, H.", year:2021,
    title:"New insights about the behavioral ecology of the coelacanth Latimeria chalumnae video recorded in the absence of humans off South Africa",
    container:"Frontiers in Marine Science 8: 755275",
    url:"https://doi.org/10.3389/fmars.2021.755275", accessed:"2026-09-19" },
  { n:79, group:"animals", authors:"Gemmell, N. J.; Rutherford, K.; Prost, S.; et al.", year:2020,
    title:"The tuatara genome reveals ancient features of amniote evolution",
    container:"Nature 584: 403-409",
    url:"https://doi.org/10.1038/s41586-020-2561-9", accessed:"2026-09-19" },
  { n:80, group:"animals", authors:"Department of Conservation Te Papa Atawhai (New Zealand)", year:null,
    title:"Tuatara",
    container:"Department of Conservation, New Zealand Government",
    url:"https://www.doc.govt.nz/nature/native-animals/reptiles-and-frogs/tuatara/", accessed:"2026-09-19" },
  { n:81, group:"animals", authors:"Hawkes, L. A.; Balachandran, S.; Batbayar, N.; Butler, P. J.; Frappell, P. B.; Milsom, W. K.; Tseveenmyadag, N.; Newman, S. H.; Scott, G. R.; Sathiyaselvam, P.; Takekawa, J. Y.; Wikelski, M.; Bishop, C. M.", year:2011,
    title:"The trans-Himalayan flights of bar-headed geese (Anser indicus)",
    container:"Proceedings of the National Academy of Sciences 108(23): 9516-9519",
    url:"https://doi.org/10.1073/pnas.1017295108", accessed:"2026-09-19" },
  { n:82, group:"animals", authors:"Hawkes, L. A.; Balachandran, S.; Batbayar, N.; et al.", year:2013,
    title:"The paradox of extreme high-altitude migration in bar-headed geese Anser indicus",
    container:"Proceedings of the Royal Society B 280(1750): 20122114",
    url:"https://doi.org/10.1098/rspb.2012.2114", accessed:"2026-09-19" },
  { n:83, group:"animals", authors:"Australian Museum (McGrouther, M.)", year:2020,
    title:"Australian Lungfish, Neoceratodus forsteri",
    container:"Australian Museum, Sydney",
    url:"https://australian.museum/learn/animals/fishes/australian-lungfish-neoceratodus-forsteri-krefft-1870/", accessed:"2026-09-19" },
  { n:84, group:"animals", authors:"University of California Museum of Paleontology", year:null,
    title:"Introduction to the Dipnoi: the lungfish",
    container:"UCMP Berkeley online exhibits",
    url:"https://ucmp.berkeley.edu/vertebrates/sarco/dipnoi.html", accessed:"2026-09-19" },
  { n:85, group:"animals", authors:"Nebenführ, M.; Arnason, U.; Janke, A.", year:2024,
    title:"Whole-genome re-sequencing of the Baikal seal and other phocid seals for a glimpse into their genetic diversity, demographic history, and phylogeny",
    container:"GigaByte 2024: gigabyte142",
    url:"https://doi.org/10.46471/gigabyte.142", accessed:"2026-09-19" },
  { n:86, group:"animals", authors:"Yakupova, A.; Tomarovsky, A.; Totikov, A.; et al.", year:2023,
    title:"Chromosome-length assembly of the Baikal seal (Pusa sibirica) genome reveals a historically large population prior to isolation in Lake Baikal",
    container:"Genes 14(3): 619",
    url:"https://doi.org/10.3390/genes14030619", accessed:"2026-09-19" },
  { n:87, group:"animals", authors:"IUCN World Heritage Outlook", year:null,
    title:"Lake Baikal",
    container:"IUCN World Heritage Outlook site assessment",
    url:"https://worldheritageoutlook.iucn.org/node/1073", accessed:"2026-09-19" },
  { n:88, group:"animals", authors:"Australian Museum", year:null,
    title:"Platypus",
    container:"Australian Museum, Sydney",
    url:"https://australian.museum/learn/animals/mammals/platypus/", accessed:"2026-09-19" },
  { n:89, group:"animals", authors:"Flannery, T. F.; Rich, T. H.; Vickers-Rich, P.; Ziegler, T.; Veatch, E. G.; Helgen, K. M.", year:2022,
    title:"A review of monotreme (Monotremata) evolution",
    container:"Alcheringa 46(1): 3-20",
    url:"https://doi.org/10.1080/03115518.2022.2025900", accessed:"2026-09-19" },
  { n:90, group:"animals", authors:"Woodburne, M. O.", year:2010,
    title:"The Great American Biotic Interchange: dispersals, tectonics, climate, sea level and holding pens",
    container:"Journal of Mammalian Evolution 17(4): 245-264",
    url:"https://doi.org/10.1007/s10914-010-9144-8", accessed:"2026-09-19" },
  { n:91, group:"animals", authors:"O'Dea, A.; Lessios, H. A.; Coates, A. G.; et al.", year:2016,
    title:"Formation of the Isthmus of Panama",
    container:"Science Advances 2(8): e1600883",
    url:"https://doi.org/10.1126/sciadv.1600883", accessed:"2026-09-19" },
  { n:92, group:"animals", authors:"Loughry, W. J.; Perez-Heydrich, C.; McDonough, C. M.; Oli, M. K.", year:2013,
    title:"Population dynamics and range expansion in nine-banded armadillos",
    container:"PLoS ONE 8(7): e68311",
    url:"https://doi.org/10.1371/journal.pone.0068311", accessed:"2026-09-19" },
  { n:93, group:"animals", authors:"U.S. Geological Survey", year:2025,
    title:"Current distribution of the nine-banded armadillo (Dasypus novemcinctus) in the United States",
    container:"USGS Publications",
    url:"https://www.usgs.gov/publications/current-distribution-nine-banded-armadillo-dasypus-novemcinctus-united-states", accessed:"2026-09-19" },
  { n:94, group:"animals", authors:"Texas Parks and Wildlife Department", year:null,
    title:"Nine-banded Armadillo (Dasypus novemcinctus)",
    container:"Texas Parks and Wildlife Department",
    url:"https://tpwd.texas.gov/huntwild/wild/species/dillo/", accessed:"2026-09-19" },
  { n:95, group:"animals", authors:"Royal Ontario Museum; Parks Canada", year:null,
    title:"Anomalocaris canadensis",
    container:"The Burgess Shale, Fossil Gallery",
    url:"https://burgess-shale.rom.on.ca/fossils/anomalocaris-canadensis/", accessed:"2026-09-19" },
  { n:96, group:"animals", authors:"Bicknell, R. D. C.; Schmidt, M.; Rahman, I. A.; Edgecombe, G. D.; Gutarra, S.; Daley, A. C.; Melzer, R. R.; Wroe, S.; Paterson, J. R.", year:2023,
    title:"Raptorial appendages of the Cambrian apex predator Anomalocaris canadensis are built for soft prey and speed",
    container:"Proceedings of the Royal Society B 290: 20230638",
    url:"https://doi.org/10.1098/rspb.2023.0638", accessed:"2026-09-19" },
  { n:97, group:"animals", authors:"Royal Ontario Museum; Parks Canada", year:null,
    title:"Opabinia regalis",
    container:"The Burgess Shale, Fossil Gallery",
    url:"https://burgess-shale.rom.on.ca/fossils/opabinia-regalis/", accessed:"2026-09-19" },
  { n:98, group:"animals", authors:"Pates, S.; Wolfe, J. M.; Lerosey-Aubril, R.; Daley, A. C.; Ortega-Hernández, J.", year:2022,
    title:"New opabiniid diversifies the weirdest wonders of the euarthropod stem group",
    container:"Proceedings of the Royal Society B 289: 20212093",
    url:"https://doi.org/10.1098/rspb.2021.2093", accessed:"2026-09-19" },
  { n:99, group:"animals", authors:"Royal Ontario Museum; Parks Canada", year:null,
    title:"Hallucigenia sparsa",
    container:"The Burgess Shale, Fossil Gallery",
    url:"https://burgess-shale.rom.on.ca/fossils/hallucigenia-sparsa/", accessed:"2026-09-19" },
  { n:100, group:"animals", authors:"Smith, M. R.; Caron, J.-B.", year:2015,
    title:"Hallucigenia's head and the pharyngeal armature of early ecdysozoans",
    container:"Nature 523: 75-78",
    url:"https://doi.org/10.1038/nature14573", accessed:"2026-09-19" },
  { n:101, group:"animals", authors:"Royal Ontario Museum; Parks Canada", year:null,
    title:"Pikaia gracilens",
    container:"The Burgess Shale, Fossil Gallery",
    url:"https://burgess-shale.rom.on.ca/fossils/pikaia-gracilens/", accessed:"2026-09-19" },
  { n:102, group:"animals", authors:"Conway Morris, S.; Caron, J.-B.", year:2012,
    title:"Pikaia gracilens Walcott, a stem-group chordate from the Middle Cambrian of British Columbia",
    container:"Biological Reviews 87: 480-512",
    url:"https://doi.org/10.1111/j.1469-185X.2012.00220.x", accessed:"2026-09-19" },
  { n:103, group:"animals", authors:"Mussini, G.; Smith, M. P.; Vinther, J.; Rahman, I. A.; Murdock, D. J. E.; Harper, D. A. T.; Dunn, F. S.", year:2024,
    title:"A new interpretation of Pikaia reveals the origins of the chordate body plan",
    container:"Current Biology 34: 2980-2989",
    url:"https://doi.org/10.1016/j.cub.2024.05.026", accessed:"2026-09-19" },
  { n:104, group:"animals", authors:"Shu, D.-G.; Luo, H.-L.; Conway Morris, S.; Zhang, X.-L.; Hu, S.-X.; Chen, L.; Han, J.; Zhu, M.; Li, Y.; Chen, L.-Z.", year:1999,
    title:"Lower Cambrian vertebrates from south China",
    container:"Nature 402: 42-46",
    url:"https://doi.org/10.1038/46965", accessed:"2026-09-19" },
  { n:105, group:"animals", authors:"Shu, D.-G.; Conway Morris, S.; Han, J.; Zhang, Z.-F.; Yasui, K.; Janvier, P.; Chen, L.; Zhang, X.-L.; Liu, J.-N.; Li, Y.; Liu, H.-Q.", year:2003,
    title:"Head and backbone of the Early Cambrian vertebrate Haikouichthys",
    container:"Nature 421: 526-529",
    url:"https://doi.org/10.1038/nature01264", accessed:"2026-09-19" },
  { n:106, group:"animals", authors:"Natural History Museum, London", year:null,
    title:"Prehistoric fish: 11 of the largest, weirdest and most significant",
    container:"Natural History Museum, Discover",
    url:"https://www.nhm.ac.uk/discover/prehistoric-fish-timeline.html", accessed:"2026-09-19" },
  { n:107, group:"animals", authors:"Holmes, J. D.; Paterson, J. R.; García-Bellido, D. C.", year:2019,
    title:"The trilobite Redlichia from the lower Cambrian Emu Bay Shale Konservat-Lagerstätte of South Australia: systematics, ontogeny and soft-part anatomy",
    container:"Journal of Systematic Palaeontology 18(4): 295-334",
    url:"https://doi.org/10.1080/14772019.2019.1605411", accessed:"2026-09-19" },
  { n:108, group:"animals", authors:"Paterson, J. R.; García-Bellido, D. C.; Jago, J. B.; Gehling, J. G.; Lee, M. S. Y.; Edgecombe, G. D.", year:2016,
    title:"The Emu Bay Shale Konservat-Lagerstätte: a view of Cambrian life from East Gondwana",
    container:"Journal of the Geological Society 173(1): 1-11",
    url:"https://doi.org/10.1144/jgs2015-083", accessed:"2026-09-19" },
  { n:109, group:"animals", authors:"Mayer, P. (Field Museum)", year:2013,
    title:"The Trilobite Paradoxides",
    container:"Field Museum blog",
    url:"https://www.fieldmuseum.org/blog/trilobite-paradoxides", accessed:"2026-09-19" },
  { n:110, group:"animals", authors:"Mahata, A.; Pates, S.", year:2026,
    title:"Revisiting abnormalities of trilobite Paradoxides davidis from Manuels River, Canada, alongside additional abnormal specimens from Porth-y-rhaw, Wales",
    container:"Royal Society Open Science 13(2): 251904",
    url:"https://doi.org/10.1098/rsos.251904", accessed:"2026-09-19" },
  { n:111, group:"animals", authors:"British Geological Survey", year:null,
    title:"Trilobites",
    container:"BGS Discovering Geology",
    url:"https://www.bgs.ac.uk/discovering-geology/fossils-and-geological-time/trilobites/", accessed:"2026-09-19" },
  { n:112, group:"animals", authors:"Van Roy, P.; Daley, A. C.; Briggs, D. E. G.", year:2015,
    title:"Anomalocaridid trunk limb homology revealed by a giant filter-feeder with paired flaps",
    container:"Nature 522: 77-80",
    url:"https://doi.org/10.1038/nature14256", accessed:"2026-09-19" },
  { n:113, group:"animals", authors:"Lerosey-Aubril, R.; Pates, S.", year:2018,
    title:"New suspension-feeding radiodont suggests evolution of microplanktivory in Cambrian macronekton",
    container:"Nature Communications 9: 3774",
    url:"https://doi.org/10.1038/s41467-018-06229-7", accessed:"2026-09-19" },
  { n:114, group:"animals", authors:"Rudkin, D. M.; Young, G. A.; Elias, R. J.; Dobrzanski, E. P.", year:2003,
    title:"The world's biggest trilobite: Isotelus rex new species from the Upper Ordovician of northern Manitoba, Canada",
    container:"Journal of Paleontology 77(1): 99-112",
    url:"https://doi.org/10.1666/0022-3360(2003)077<0099:TWBTIR>2.0.CO;2", accessed:"2026-09-19" },
  { n:115, group:"animals", authors:"Morgan, A. V. (University of Waterloo, Earth Sciences Museum)", year:2003,
    title:"The world's largest trilobite; the Waterloo Connection!",
    container:"Wat On Earth, University of Waterloo",
    url:"https://uwaterloo.ca/wat-on-earth/news/worlds-largest-trilobite-waterloo-connection", accessed:"2026-09-19" },
  { n:116, group:"animals", authors:"Klug, C.; Fuchs, D.; Pohle, A.; Korn, D.; De Baets, K.; Hoffmann, R.; Ware, D.; Ward, P. D.", year:2025,
    title:"Cephalopod body size and macroecology through deep time",
    container:"Scientific Reports 15: 30736",
    url:"https://doi.org/10.1038/s41598-025-13940-1", accessed:"2026-09-19" },
  { n:117, group:"animals", authors:"Klug, C.; De Baets, K.; Kröger, B.; Bell, M. A.; Korn, D.; Payne, J. L.", year:2015,
    title:"Normal giants? Temporal and latitudinal shifts of Palaeozoic marine invertebrate gigantism and global change",
    container:"Lethaia 48(2): 267-288",
    url:"https://doi.org/10.1111/let.12104", accessed:"2026-09-19" },
  { n:118, group:"animals", authors:"Pradel, A.; Sansom, I. J.; Gagnier, P.-Y.; Cespedes, R.; Janvier, P.", year:2007,
    title:"The tail of the Ordovician fish Sacabambaspis",
    container:"Biology Letters 3(1): 72-75",
    url:"https://doi.org/10.1098/rsbl.2006.0557", accessed:"2026-09-19" },
  { n:119, group:"animals", authors:"Choo, B.; Zhu, M.; Zhao, W.; Jia, L.; Zhu, Y.", year:2014,
    title:"The largest Silurian vertebrate and its palaeoecological implications",
    container:"Scientific Reports 4: 5242",
    url:"https://doi.org/10.1038/srep05242", accessed:"2026-09-19" },
  { n:120, group:"animals", authors:"Hagiwara, W.; Sallan, L.", year:2026,
    title:"Mass extinction triggered the early radiations of jawed vertebrates and their jawless relatives (gnathostomes)",
    container:"Science Advances 12(2): eaeb2297",
    url:"https://doi.org/10.1126/sciadv.aeb2297", accessed:"2026-09-19" },
  { n:121, group:"animals", authors:"Lamsdell, J. C.; Briggs, D. E. G.; Liu, H. P.; Witzke, B. J.; McKay, R. M.", year:2015,
    title:"The oldest described eurypterid: a giant Middle Ordovician (Darriwilian) megalograptid from the Winneshiek Lagerstätte of Iowa",
    container:"BMC Evolutionary Biology 15: 169",
    url:"https://doi.org/10.1186/s12862-015-0443-9", accessed:"2026-09-19" },
  { n:122, group:"animals", authors:"Briggs, D. E. G.; Liu, H. P.; McKay, R. M.; Witzke, B. J.", year:2018,
    title:"The Winneshiek biota: exceptionally well-preserved fossils in a Middle Ordovician impact crater",
    container:"Journal of the Geological Society 175(6): 865-874",
    url:"https://doi.org/10.1144/jgs2018-101", accessed:"2026-09-19" },
  { n:123, group:"animals", authors:"Gabbott, S. E.; Browning, C.; Theron, J. N.; Whittle, R. J.", year:2017,
    title:"The late Ordovician Soom Shale Lagerstätte: an extraordinary post-glacial fossil and sedimentary record",
    container:"Journal of the Geological Society 174(1): 1-9",
    url:"https://doi.org/10.1144/jgs2016-076", accessed:"2026-09-19" },
  { n:124, group:"animals", authors:"Theron, J. N.; Rickards, R. B.; Aldridge, R. J.", year:1990,
    title:"Bedding plane assemblages of Promissum pulchrum, a new giant Ashgill conodont from the Table Mountain Group, South Africa",
    container:"Palaeontology 33(3): 577-594",
    url:"https://palass.org/publications/palaeontology-journal/archive/33/3/article_pp577-594", accessed:"2026-09-19" },
  { n:125, group:"animals", authors:"Gabbott, S. E.; Aldridge, R. J.; Theron, J. N.", year:1995,
    title:"A giant conodont with preserved muscle tissue from the Upper Ordovician of South Africa",
    container:"Nature 374: 800-803",
    url:"https://doi.org/10.1038/374800a0", accessed:"2026-09-19" },
  { n:126, group:"animals", authors:"British Geological Survey", year:null,
    title:"Graptolites",
    container:"BGS Discovering Geology",
    url:"https://www.bgs.ac.uk/discovering-geology/fossils-and-geological-time/graptolites/", accessed:"2026-09-19" },
  { n:127, group:"animals", authors:"Amgueddfa Cymru, Museum Wales", year:2007,
    title:"460-million-year-old relatives from Wales and Belgium reunited",
    container:"Museum Wales articles",
    url:"https://museum.wales/articles/2007-07-26/460-million-year-old-relatives-from-Wales-and-Belgium-reunited/", accessed:"2026-09-19" },
  { n:128, group:"animals", authors:"Brookfield, M. E.; Catlos, E. J.; Suarez, S. E.", year:2020,
    title:"Myriapod divergence times differ between molecular clock and fossil evidence: U/Pb zircon ages of the earliest fossil millipede-bearing sediments and their significance",
    container:"Historical Biology 33(10): 2009-2013",
    url:"https://doi.org/10.1080/08912963.2020.1761351", accessed:"2026-09-19" },
  { n:129, group:"animals", authors:"Jackson School of Geosciences, University of Texas at Austin", year:2020,
    title:"World's Oldest Bug is Fossil Millipede from Scotland",
    container:"Jackson School of Geosciences news",
    url:"https://www.jsg.utexas.edu/news/2020/05/worlds-oldest-bug-is-fossil-millipede-from-scotland/", accessed:"2026-09-19" },
  { n:130, group:"animals", authors:"Suarez, S. E.; Brookfield, M. E.; Catlos, E. J.; Stöckli, D. F.", year:2017,
    title:"A U-Pb zircon age constraint on the oldest-recorded air-breathing land animal",
    container:"PLoS ONE 12(6): e0179262",
    url:"https://doi.org/10.1371/journal.pone.0179262", accessed:"2026-09-19" },
  { n:131, group:"animals", authors:"Jeram, A. J.; Selden, P. A.; Edwards, D.", year:1990,
    title:"Land animals in the Silurian: arachnids and myriapods from Shropshire, England",
    container:"Science 250(4981): 658-661",
    url:"https://doi.org/10.1126/science.250.4981.658", accessed:"2026-09-19" },
  { n:132, group:"animals", authors:"Dunlop, J. A.", year:1996,
    title:"A trigonotarbid arachnid from the Upper Silurian of Shropshire",
    container:"Palaeontology 39(3): 605-614",
    url:"https://palass.org/publications/palaeontology-journal/archive/39/3/article_pp605-614", accessed:"2026-09-19" },
  { n:133, group:"animals", authors:"Braddy, S. J.; Poschmann, M.; Tetlie, O. E.", year:2008,
    title:"Giant claw reveals the largest ever arthropod",
    container:"Biology Letters 4(1): 106-109",
    url:"https://doi.org/10.1098/rsbl.2007.0491", accessed:"2026-09-19" },
  { n:134, group:"animals", authors:"U.S. National Park Service", year:null,
    title:"Fossils of the 2013 National Fossil Day Artwork",
    container:"NPS article",
    url:"https://www.nps.gov/articles/fossils-of-the-2013-national-fossil-day-artwork.htm", accessed:"2026-09-19" },
  { n:135, group:"animals", authors:"Royal Ontario Museum", year:null,
    title:"Fossil sea scorpion (Eurypterus remipes)",
    container:"ROM Collections online",
    url:"https://collections.rom.on.ca/objects/1620768/fossil-sea-scorpion-eurypterus-remipes", accessed:"2026-09-19" },
  { n:136, group:"animals", authors:"New York State Museum", year:null,
    title:"Eurypterid",
    container:"New York State Museum, exhibition windows",
    url:"https://nysm.nysed.gov/exhibitions/windows/eurypterid", accessed:"2026-09-19" },
  { n:137, group:"animals", authors:"Zhu, M.; Yu, X.; Ahlberg, P. E.; Choo, B.; Lu, J.; Qiao, T.; Qu, Q.; Zhao, W.; Jia, L.; Blom, H.; Zhu, Y.", year:2013,
    title:"A Silurian placoderm with osteichthyan-like marginal jaw bones",
    container:"Nature 502: 188-193",
    url:"https://doi.org/10.1038/nature12617", accessed:"2026-09-19" },
  { n:138, group:"animals", authors:"Cui, X.; Friedman, M.; Yu, Y.; Zhu, Y.-A.; Zhu, M.", year:2023,
    title:"Bony-fish-like scales in a Silurian maxillate placoderm",
    container:"Nature Communications 14: 7622",
    url:"https://doi.org/10.1038/s41467-023-43557-9", accessed:"2026-09-19" },
  { n:139, group:"animals", authors:"Pimiento, C.; Kocáková, K.; Mathes, G. H.; Argyriou, T.; Cadena, E.-A.; Cooper, J. A.; Cortés, D.; Field, D. J.; Klug, C.; Scheyer, T. M.; Valenzuela-Toro, A. M.; and others", year:2024,
    title:"The extinct marine megafauna of the Phanerozoic",
    container:"Cambridge Prisms: Extinction 2: e7",
    url:"https://doi.org/10.1017/ext.2024.12", accessed:"2026-09-19" },
  { n:140, group:"animals", authors:"Black Country UNESCO Global Geopark", year:null,
    title:"Wren's Nest National Nature Reserve",
    container:"Black Country Geopark, sites to see",
    url:"https://blackcountrygeopark.dudley.gov.uk/sites-to-see/wrens-nest-national-nature-reserve/", accessed:"2026-09-19" },
  { n:141, group:"animals", authors:"Dudley Metropolitan Borough Council", year:null,
    title:"Wren's Nest National Nature Reserve",
    container:"Dudley Council, nature reserves",
    url:"https://www.dudley.gov.uk/things-to-do/nature-reserves/wrens-nest-national-nature-reserve/", accessed:"2026-09-19" }
];

/* PhyloPic silhouettes used in the Animals panel, one line per image.
   Only CC0 and CC BY images are used. */
const SILHOUETTES = [
  { genus:"Akmonistion", file:"img/animals/akmonistion.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Mike Coates (drawing) and Richard Dearden (modification)", imagePage:"https://www.phylopic.org/images/63149e81-d5e2-4983-869d-3b02427082d0", note:null },
  { genus:"Anomalocaris", file:"img/animals/anomalocaris.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Amy Beauvois", imagePage:"https://www.phylopic.org/images/c3b75f48-d943-422b-9234-dc56b39ae01a", note:null },
  { genus:"Anser", file:"img/animals/anser.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Rebecca Groom", imagePage:"https://www.phylopic.org/images/0c03eac4-f4ac-4df7-86f2-6653634de0b4", note:null },
  { genus:"Apteryx", file:"img/animals/apteryx.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Traver", imagePage:"https://www.phylopic.org/images/ad7d0f80-889e-4dba-a89d-c864f2f48184", note:null },
  { genus:"Arthropleura", file:"img/animals/arthropleura.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Jun", imagePage:"https://www.phylopic.org/images/7fd55470-802d-4a0a-9bdd-73e2f828c5a6", note:null },
  { genus:"Basilosaurus", file:"img/animals/basilosaurus.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Michael Tripoli", imagePage:"https://www.phylopic.org/images/aeffb6cf-825a-4c12-9801-a4a46226add5", note:null },
  { genus:"Bothriolepis", file:"img/animals/bothriolepis.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Coombs", imagePage:"https://www.phylopic.org/images/5ac3e6ad-bb40-4917-8cfd-810e4e3ba434", note:null },
  { genus:"Dasypus", file:"img/animals/dasypus.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Traver", imagePage:"https://www.phylopic.org/images/5d59b5ce-c1dd-40f6-b295-8d2629b9775e", note:null },
  { genus:"Dimetrodon", file:"img/animals/dimetrodon.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Alessio Ciaffi", imagePage:"https://www.phylopic.org/images/b9b73c89-7609-4524-b068-7c7c7f566979", note:null },
  { genus:"Dromiciops", file:"img/animals/dromiciops.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Sarah Werning", imagePage:"https://www.phylopic.org/images/dde4f926-c04c-47ef-a337-927ceb36e7ef", note:null },
  { genus:"Dunkleosteus", file:"img/animals/dunkleosteus.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Russell Engelman", imagePage:"https://www.phylopic.org/images/3c9a7513-5b3f-463c-851c-148da2ab4bab", note:null },
  { genus:"Endoceras", file:"img/animals/endoceras.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Tyler Greenfield", imagePage:"https://www.phylopic.org/images/88edcbd6-dd46-4e4a-ba1b-20a71f0cfdeb", note:null },
  { genus:"Gastornis", file:"img/animals/gastornis.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Colin McElroy (vectorized by Andrew Schwartz)", imagePage:"https://www.phylopic.org/images/4e08a814-ee4b-4179-a061-e3bd1c1e51da", note:null },
  { genus:"Haikouichthys", file:"img/animals/haikouichthys.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Scott Hartman", imagePage:"https://www.phylopic.org/images/0515c3e8-d194-4bad-a9e9-6d65759904f2", note:"Silhouette is Myllokunmingia fengjiaoa, the other Chengjiang fish of the same family (Myllokunmingiidae), which some authors treat as the same species. The only Haikouichthys image on PhyloPic is CC BY-SA and was not used." },
  { genus:"Helicoprion", file:"img/animals/helicoprion.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Olof Moleman", imagePage:"https://www.phylopic.org/images/2dc67937-9756-4639-91d1-77f5d748fe9e", note:"Silhouette is of Helicoprion davisii; the body outline is a reconstruction, since only whorls and jaw cartilage are known." },
  { genus:"Isotelus", file:"img/animals/isotelus.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Tyler Greenfield", imagePage:"https://www.phylopic.org/images/43e10358-37a5-495f-910a-202532a32f29", note:"Silhouette is Pseudogygites latimarginatus, a member of the same family (Asaphidae). PhyloPic has no Isotelus image." },
  { genus:"Knightia", file:"img/animals/knightia.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Caleb M. Gordon", imagePage:"https://www.phylopic.org/images/b275174b-3db2-4b19-94b7-11b536caacdc", note:null },
  { genus:"Latimeria", file:"img/animals/latimeria.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Chuanixn Yu", imagePage:"https://www.phylopic.org/images/12c38a8a-6d68-4af3-ada3-05cafdfc25c2", note:null },
  { genus:"Lemur", file:"img/animals/lemur.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Ferran Sayol", imagePage:"https://www.phylopic.org/images/8a187391-82a3-4d9b-a402-3a310bf7dc38", note:null },
  { genus:"Lystrosaurus", file:"img/animals/lystrosaurus.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Matt Celeskey", imagePage:"https://www.phylopic.org/images/03efb48d-b735-4812-bf65-39279d9f7067", note:"Silhouette is of Lystrosaurus murrayi, one of the smaller Triassic species of the same genus." },
  { genus:"Meganeura", file:"img/animals/meganeura.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/b7b2895c-f9c3-436a-8efa-d80b14fe0918", note:null },
  { genus:"Moschops", file:"img/animals/moschops.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Ryan Santos Soledade", imagePage:"https://www.phylopic.org/images/b5f52159-e0a7-4054-88a7-3836ace24f49", note:null },
  { genus:"Neoceratodus", file:"img/animals/neoceratodus.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Roberto Díaz Sibaja", imagePage:"https://www.phylopic.org/images/3bfadee3-c4c5-408e-a1b8-e09bec80bc7f", note:null },
  { genus:"Onychonycteris", file:"img/animals/onychonycteris.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"T. Michael Keesey", imagePage:"https://www.phylopic.org/images/104c97b7-74da-418b-8d0a-655728bed23f", note:null },
  { genus:"Opabinia", file:"img/animals/opabinia.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Amy Beauvois", imagePage:"https://www.phylopic.org/images/dfb89878-9fc7-4c76-9783-252f984bb5ad", note:null },
  { genus:"Ornithorhynchus", file:"img/animals/ornithorhynchus.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Traver", imagePage:"https://www.phylopic.org/images/61932f57-1fd2-49d9-bb86-042d6005581a", note:null },
  { genus:"Pakicetus", file:"img/animals/pakicetus.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Michael Tripoli", imagePage:"https://www.phylopic.org/images/2a24db93-00dc-4dfb-b338-35c66154b6bf", note:null },
  { genus:"Palaeocharinus", file:"img/animals/palaeocharinus.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/19d19934-8486-4e31-9f6c-41db3641f377", note:null },
  { genus:"Paraceratherium", file:"img/animals/paraceratherium.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Traver", imagePage:"https://www.phylopic.org/images/12fc9c0f-3b9e-4cc1-a184-df6abfbbe3e9", note:null },
  { genus:"Pelagornis", file:"img/animals/pelagornis.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/04316546-fd53-4755-bced-c13dd35c1754", note:"Silhouette is Pelagornis chilensis, the same genus; the entry describes P. sandersi." },
  { genus:"Pentecopterus", file:"img/animals/pentecopterus.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"J. C. Lamsdell, D. E. G. Briggs, H. P. Liu, B. J. Witzke & R. M. McKay", imagePage:"https://www.phylopic.org/images/ed02ccb0-5820-44a7-b46a-1a16a8894128", note:null },
  { genus:"Pikaia", file:"img/animals/pikaia.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Giovanni Mussini", imagePage:"https://www.phylopic.org/images/7ac9ebfa-59bf-4d68-ada7-651ef6da38f0", note:null },
  { genus:"Pusa", file:"img/animals/pusa.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Margot Michaud", imagePage:"https://www.phylopic.org/images/d6b55d96-57fd-492a-bd11-8286384fffb5", note:"No silhouette of Pusa sibirica; this is the ringed seal, Pusa hispida, of the same genus." },
  { genus:"Sacabambaspis", file:"img/animals/sacabambaspis.svg", licence:"CC BY 4.0", licenceUrl:"https://creativecommons.org/licenses/by/4.0/", contributor:"Petr Menshikov (original illustration), T. Michael Keesey (vectorization)", imagePage:"https://www.phylopic.org/images/a64284b6-f882-4804-b43a-6d3f154c3e0c", note:null },
  { genus:"Sphenodon", file:"img/animals/sphenodon.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:"Steven Traver", imagePage:"https://www.phylopic.org/images/f2a5ae73-c899-4e47-b0ad-b6eac3a99350", note:null },
  { genus:"Tiktaalik", file:"img/animals/tiktaalik.svg", licence:"CC0 1.0", licenceUrl:"https://creativecommons.org/publicdomain/zero/1.0/", contributor:null, imagePage:"https://www.phylopic.org/images/10a9bdee-2c86-4f13-a8ae-5ff92dbed2a9", note:null },
  { genus:"Titanoboa", file:"img/animals/titanoboa.svg", licence:"CC BY 3.0", licenceUrl:"https://creativecommons.org/licenses/by/3.0/", contributor:"Nobu Tamura (modified by T. Michael Keesey)", imagePage:"https://www.phylopic.org/images/beca4a24-33ef-4659-a20f-7d6835703c1c", note:null }
];

function sourceByNumber(n){ return SOURCES.find(s => s.n === n); }
function sourceCitation(s){
  return s.authors + (s.year ? " (" + s.year + "). " : ". ") + s.title + ". " + s.container + ".";
}
